### ISSUE TITLE
UI for Autocomplete and linter trip over themselves

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#103]
You can have linter errors and autocomplete suggestions on top of each other on the UI.

**Comment by ctolkien** [comment]
Ref #43 

There are other UI pieces that we want to display such as refactoring, full method information, overload information, return types.. etc.

**Comment by david-driscoll** [comment]
This seems to be better with the latest atomlinter, closing for now, we can address again if it becomes a big problem.
