### ISSUE TITLE
Cleanup klr threads on editor shutdown or toggle-off

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#111]
The roslyn server can kill the klr thread with the right parmeters, probably editor pid.  At the moment omnisharp-atom does not do this, resulting in orphaned klr processes.

**Comment by david-driscoll** [comment]
With stdio I did hand off the node process.pid to the server.  So far it seems that whenever the atom process goes away the server now kills itself too.

**Comment by ctolkien** [comment]
Seems fixed to me as well. There are two klr processes, but no more get spawned when you toggle the server. No more left when you close atom.

**Comment by sgwill** [comment]
Oh, I'll check. That's great!

**Comment by nosami** [comment]
There should be 2 klr processes. One is OmniSharp, the other is DTH (Design Time Host) that OmniSharp communicates with.

**Comment by sgwill** [comment]
Yep, I'm seeing those same two processes getting reused now, instead of new ones on each toggle. Now we just need to be able to kill them completely.

**Comment by ctolkien** [comment]
When I shutdown or restart atom, I'm seeing them die on Windows.

________________________________

**Comment by sgwill** [comment]
Yes, but toggle should also kill them. They are being killed when Atom is closed for me, too.

**Comment by sgwill** [comment]
Looks to me like we're back to orphaning klr threads, but now I think this belongs in `omnisharp-node-client`. I'm going to close here and re-open there.
