### ISSUE TITLE
Failed to load package: "Cannot find module 'lodash'"

### ISSUE THREAD

**Issue by aggieben** [OmniSharp/omnisharp-atom#112]
I'm trying to load the `master` version by cloning directly into `~/.atom/packages`, but when I start atom I get the following:

![image](https://cloud.githubusercontent.com/assets/1321/7260150/bc0ac112-e82d-11e4-9199-da4387d0d035.png)

Any ideas?

p.s. - the link at the bottom noting that "this issue has already been reported" is referring to #97, apparently matching by title, but that issue does not seem related to this one.

**Comment by aggieben** [comment]
Oh, stupid: nevermind.  I forgot to run `npm install`!

**Comment by sgwill** [comment]
After you pull from master, you need to install the node modules. Try running `npm install`

**Comment by sgwill** [comment]
Beat me to it. Good luck!
