### ISSUE TITLE
Offer "File -> New Project" experiencing using omnisharp/generator-aspnet

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-atom#114]
@davidfowl was talking about the getting started experience with Omnisharp in general.

Could we offer a "File -> New Project" experience in Atom?  Either with a simple command in our packages menu, or even adding a new Omnisharp heading (if possible?).

I figure since atom is already running on top of Node we should be able to leverage https://github.com/OmniSharp/generator-aspnet in someway so that we're not duplicating templates.

**Comment by sgwill** [comment]
Is there a yeoman package for Atom? As you say, it'd be great to popup and use https://github.com/OmniSharp/generator-aspnet

**Comment by david-driscoll** [comment]
Not that I'm aware of... the typical case is they are usually run from the command line.  While I'm not adverse to that myself, if we want to make the "introductory experience" better, we should see if there is some way to call into the generator, even if we just supply the information ourselves.

**Comment by sgwill** [comment]
I completely agree, both with Introductory Experience, and with trying to re-use the generator. Do we need to be able to support pre-vNext, though?

**Comment by david-driscoll** [comment]
Since the generator is currently only vNext, then we could as the first iteration only support vNext, and then expand support beyond that later.  Anything beyond what the generator offers today, would be a significant investment though.

**Comment by sgwill** [comment]
Ahh, good point. :+1: I like this idea.

**Comment by willl** [comment]
We can have a look at this run command package. https://atom.io/packages/run-command

It hasn't been updated for awhile though, so there will likely be deprecation warnings etc... But we can probably fork it and work with it to call the relevant yeoman generator.

**Comment by david-driscoll** [comment]
Looks like yeoman offers the ability to integrate outside of the terminal, so we could basically offer the ability to run any yeoman generator from the atom UI.

http://yeoman.io/authoring/integrating-yeoman.html

**Comment by sgwill** [comment]
This is merged!
