### ISSUE TITLE
Automatically install dependencies if not installed

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#116]
To make it nicer for our users, install `autocomplete-plus` or `linter` if they aren't installed. 

See atom-typescript for ideas https://github.com/TypeStrong/atom-typescript/blob/eec59e111de711653d686794a872730d6994da0d/lib/main/atomts.ts#L237

**Comment by david-driscoll** [comment]
:+1:

**Comment by ctolkien** [comment]
Can we leverage something like:
https://atom.io/packages/update-package-dependencies

?
