### ISSUE TITLE
Snippet support as part of autocomplete

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#117]
We must overtake emacs.

![emacs screenie](https://cloud.githubusercontent.com/assets/667194/4607759/1cd4163a-525e-11e4-802c-9620427778dc.gif)

**Comment by nosami** [comment]
Omnisharp-roslyn tests here https://github.com/OmniSharp/omnisharp-roslyn/blob/master/tests/OmniSharp.Tests/SnippetFacts.cs

The server generates the snippet placeholders. They are the standard format used by every editor I've ever seen. You just need to figure out how to inject those into the editor when completion finishes.

**Comment by ctolkien** [comment]
Investigate using https://github.com/atom-community/autocomplete-snippets

**Comment by ctolkien** [comment]
This will be addressed with #122 which has snippet support.

**Comment by ctolkien** [comment]
Closing as dupe, following along in the above ticket.
