### ISSUE TITLE
Missing icons for delegate and interface types

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#118]
These are currently being requested but triggered 404's.

**Comment by sgwill** [comment]
Those icons appear to be missing completely. Where did you get the original set, @ctolkien

**Comment by ctolkien** [comment]
I think someone from MS hooked us up, perhaps @sayedihashimi  ?

There's also `NamedType`, `Parameter`, and `Local` that we're currently skipping:
https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/lib/completion-provider.ts#L44

**Comment by nosami** [comment]
We changed NamedType to be 'Class', 'Struct' etc. not sure about the others.

**Comment by sayedihashimi** [comment]
Can you check to see if the icons you need are in https://www.dropbox.com/s/64ndh40nkzrcpyn/Sayed_OmniSharpIcons_ToClient.zip?dl=0. If not then please list the icons that you need as well as a sample image from VS.

**Comment by ctolkien** [comment]
Delegate appears to use the same icon as 'keyword' in VS (which we have, so that should be fine).

Interface seems the be the only one we're missing that I can spot.

![](http://i.imgur.com/qaYjmvg.png)

**Comment by sayedihashimi** [comment]
OK I have put the request in. Stay tuned.

**Comment by sayedihashimi** [comment]
Interface images are attached here, I've also added them to the full set of icons at https://www.dropbox.com/s/64ndh40nkzrcpyn/Sayed_OmniSharpIcons_ToClient.zip?dl=0.
![interface_blue_64x](https://cloud.githubusercontent.com/assets/1283154/7352597/850dfd6c-ecc1-11e4-8ba9-d8d544cef0e1.png)
![interface_blue_16x](https://cloud.githubusercontent.com/assets/1283154/7352596/850dfcb8-ecc1-11e4-83d2-1da5ac9f43a9.png)
![interface_blue_32x](https://cloud.githubusercontent.com/assets/1283154/7352595/850c3f90-ecc1-11e4-979b-de6faee00b37.png)

**Comment by nosami** [comment]
Thanks Sayed :+1:
