### ISSUE TITLE
intellisense should show properties first

### ISSUE THREAD

**Issue by luisrudge** [OmniSharp/omnisharp-atom#120]
![image](https://cloud.githubusercontent.com/assets/941075/7266554/d460bbfa-e881-11e4-9030-49e909aef16f.png)

![image](https://cloud.githubusercontent.com/assets/941075/7266555/d671a03a-e881-11e4-81f7-750e4320210a.png)

**Comment by AndersNS** [comment]
Visual Studio doesn't do it like that for me. Nor does any other autocompletion I have used.  Maybe make it configurable?

![image](https://cloud.githubusercontent.com/assets/1052521/7296061/8aa45f76-e9bc-11e4-8501-1ac5b03c4dd7.png)

**Comment by nosami** [comment]
Yeah... it's easy to implement, but I'm not sure that we should. I don't see any value from it.

We have fuzzy searching on completions too, so that when you type a couple of characters, we have to rank them.

**Comment by luisrudge** [comment]
Well, I guess it's a resharp thing then. But it makes lots of sense to group things, Specially because the icons are easily distinguishable, since they're on the right.

**Comment by nosami** [comment]
Fuzzy searching means they are ranked by relevancy. You can't have both.

**Comment by luisrudge** [comment]
Can you change the icons to the left? That would be an improvement. If you can show properties first via an option or something, that would be great too

**Comment by ctolkien** [comment]
@luisrudge  That's being handled with the migration to Autocomplete v2 (https://github.com/OmniSharp/omnisharp-atom/issues/122)

**Comment by luisrudge** [comment]
awesome thanks!

**Comment by ctolkien** [comment]
Anything left to action from this?

(left to action? geez I sound like some annoying [seagull manager](http://www.urbandictionary.com/define.php?term=seagull%20manager))
