### ISSUE TITLE
Update Autocomplete-Plus to use 2.0 API

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#122]
- [x] Snippet support (to stick it to @nosami)
- [ ] Replace missing/borked icons (some are heavily left aligned, makes sure these fit in with ecosystem)
- [x] Description text
~~- [ ] Description 'Read More' (possible links to documentation?)~~
~~- [ ] Issues with word at max width/overflow, doesn't float properly?~~ issue upstream
- [ ] Don't autocomplete on `;`
- [x] Exclude built in provider (or anything lower priority)
- [x] Don't explode if Omnisharp isn't started.
- [x] Content return vars to html characters
- [x] Override default styling to better suit C#'s verbosity!
- [ ] Only use snippet support if one is supplied, else fall back to text.
- [x] Need a null value check, throws if no value.

Provider API2 docs:
https://github.com/atom-community/autocomplete-plus/wiki/Provider-API

**Comment by ctolkien** [comment]
Current status:
![](http://i.imgur.com/Q3cUg29.gif)

**Comment by david-driscoll** [comment]
:laughing:

**Comment by ctolkien** [comment]
RE: Missing icons: https://github.com/OmniSharp/omnisharp-atom/issues/118#issuecomment-95707081

**Comment by ctolkien** [comment]
RE: Autocomplete styling:
https://github.com/atom-community/autocomplete-plus/issues/405

**Comment by ctolkien** [comment]
Closing, close enough!
