### ISSUE TITLE
Omnisharp-Atom should auto-start when you open a .cs file and it isn't running.

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#123]

**Comment by willl** [comment]
Not just .cs files, but .csx (scriptcs) needs to be detected too. 

Can probably call the text editor's getGrammer method. https://atom.io/docs/api/v0.194.0/TextEditor#instance-getGrammar

**Comment by Mpdreamz** [comment]
I'm on the fence about this, I rather we keep it an explicit action to turn on the server or atleast make this an option that can be turned off :)

**Comment by sgwill** [comment]
I think at the very least it'd be a nice option. We can always change our mind about whether or not it's enabled by default.

**Comment by david-driscoll** [comment]
We can always have a setting as part of the settings page.

**Comment by nosami** [comment]
I'd prefer to have it auto-start. The default keybind for toggle doesn't work at all on linux.

**Comment by davidfowl** [comment]
+1 Auto start on certain files and have those files be configurable. Default set:

.csproj, project.json, .cs, .csx
