### ISSUE TITLE
TextEditor.on is deprecated

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/omnisharp-atom#126]
From the cop:
> TextEditor::on is deprecated. Use documented event subscription methods instead.

```
TextEditor.on (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3037:11)
<unknown> (/Users/piotrblazejewicz/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.coffee:16:15)
```
I believe that in never version not yet released via apm that is relevant to:
https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/go-to-definition.ts#L21-L23d

OmniSharp: v.0.3.0
Atom: Version 0.192.0 (0.192.0)

Thanks!

**Comment by david-driscoll** [comment]
Yeah, this wasn't a problem with the TypeScript version as the declarations made the deprecation's show up fairly easy.

This was fixed in 0.4.0
