### ISSUE TITLE
Better syntax highlighting

### ISSUE THREAD

**Issue by Mpdreamz** [OmniSharp/omnisharp-atom#127]
It be nice if we can improve the current highlighter to do a better job highlighting 

compare atom:

![image](https://cloud.githubusercontent.com/assets/245275/7286205/634209dc-e94a-11e4-9bfe-0ef2f9ab2203.png)

with visual studio and resharper:

![image](https://cloud.githubusercontent.com/assets/245275/7286444/4b7f1d92-e94c-11e4-9983-51d3f199b940.png)

We should be able to highlight much better and smarter.

https://discuss.atom.io/t/dynamic-grammers/14927/3

https://atom.io/packages/language-javascript-semantic

**Comment by nosami** [comment]
Roslyn has an api for this. We should use it.

**Comment by ctolkien** [comment]
Current syntax highlighting isn't provided by this package, but by https://github.com/atom/language-csharp (which is in atom core)

**Comment by sgwill** [comment]
Additional: Typescript appears to be doing this dynamically https://discuss.atom.io/t/defining-a-language-grammar-via-code/14784/2, which points to https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/typescriptGrammar.ts

**Comment by david-driscoll** [comment]
So I looked into this on Sunday, and I just couldn't get async tokenization to work.

It might be possible to do with the standard tokenization, I'm going to look into that this week.

**Comment by david-driscoll** [comment]
Landed as 7f69880cd9d
