### ISSUE TITLE
Open Pane if collapsed on Find Usages/etc

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#128]
If the pane is closed when a user selects `Goto-Definition` or `Find Usages`, expand the pane.

Currently it will select the correct tab, but not expand the pane.

**Comment by sgwill** [comment]
Goto-definition doesn't actually need this. It's for `Find Usings`, `Build`, and eventually for #106 `Go To Implementation` when there are more than 1 result.

**Comment by willl** [comment]
Perhaps for `Find Usings` we should open it in a new window?

In Atom, if you do CTRL+SHIFT+F, it'll do a find in all files which will open up a `Project Find Results` window.

R# in VS kinda does the same (a dockable results window) when you do `Find Usages`.

**Comment by sgwill** [comment]
I'm open to that. Perhaps we can make it a setting. I usually prefer a pane somewhere that stays visibile while wandering around those usings.

**Comment by david-driscoll** [comment]
I kind of like the resharper way of doing it.  In the `Find Results` window there are then a set of tabs for each result set you've searched for.  Something like would be cool.
