### ISSUE TITLE
format on saving

### ISSUE THREAD

**Issue by luisrudge** [OmniSharp/omnisharp-atom#136]
that would be great :)

**Comment by nosami** [comment]
Would need to be configurable as not everyone would want this.

**Comment by luisrudge** [comment]
Yeah. I'll do that one :)

**Comment by ctolkien** [comment]
Yeah we need a whole settings bit to get this in.. should be straight forward though as Atom has a framework for it.

Get to coding @luisrudge  :smile:

**Comment by davidfowl** [comment]
Noo format on save. At least make it configurable. See https://github.com/OmniSharp/omnisharp-atom/issues/151 as well.

**Comment by nosami** [comment]
@luisrudge v0.4.22 has format on keystroke ; and }

Care to try it and see if you still want format on save?

**Comment by luisrudge** [comment]
@nosami that's totally not required now :) format on keystroke is awesome!

**Comment by oleyb** [comment]
Sorry, this is slightly off topic, but is it currently possible to configure how the code formatting functionality formats code? For example, having it keep opening braces on the same line with control blocks?

**Comment by david-driscoll** [comment]
There are configurations in Omnisharp-Roslyn (that we have yet to
expose!).  I'm not sure if that is a feature (keeping brace on the same
line) as that is not typical of C# code bases.
