### ISSUE TITLE
Autocomplete box is misaligned

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#137]
![image](https://cloud.githubusercontent.com/assets/95136/7311446/5b8d9e48-e9f1-11e4-8f38-815b153fc13c.png)

**Comment by nosami** [comment]
Looks good to me.

**Comment by ctolkien** [comment]
The actual bit you are autocompleting lines up with your cursor. Atom has concept of the type of the returned value being to the "left" of that. This matches the rest of the ecosystem. Need to discuss how closely to match VS.

I should note that the return type is optional.

**Comment by davidfowl** [comment]
It's a big waste of space:

![image](https://cloud.githubusercontent.com/assets/95136/7313664/50fcd3de-ea11-11e4-8f7a-290151c58de9.png)

**Comment by ctolkien** [comment]
@davidfowl  thoughts w/o the return type?

![](http://i.imgur.com/vSqGnH5.png)

**Comment by nosami** [comment]
Looks nicer... but the return type is useful information. Why not put it on
the right? You don't need "Method", "Class" etc when you have the icons.

**Comment by ctolkien** [comment]
Again, is about fitting in with the ecosystem, right label is to be used for ": An indicator (e.g. function, variable) denoting the "kind" of suggestion this represents".

Am wary of straying off course here.

**Comment by david-driscoll** [comment]
I kinda like the return type to the right of the method call.

That said VS doesn't even in the give return type (there is a tooltip that shows up with the return type information if you wait though).

**Comment by davidfowl** [comment]
A few things:
- The box shouldn't jump around and resize in a jerky manner. This is one of the reasons I dislike the sublime plugin.
- It's just too big. I have a 13" MBP and it can sometimes take up the entire editor window.
- Showing the return type and type of thing is also fine. I dunno if we need icons and text, maybe that's fine?

**Comment by jmkelly** [comment]
I'm for moving the type to the right of the method call.  The blank space where there return type will bring down the container size considerably.

I've knocked font back on mine to 0.7em, seems to display a little nicer, doesn't overpower the code quite so much.  

![image](https://cloud.githubusercontent.com/assets/124026/7363990/94ce7e1c-edc4-11e4-8283-1eb6d60fa060.png)

**Comment by willl** [comment]
Should probably use the same CSS class as the text in the linter status bar (.text-smaller).

https://github.com/AtomLinter/Linter/blob/dea8a89cfcb64f1f210189d1f83e0dfcae06acbc/lib/statusbar-view.coffee#L10

Which you can see in action here:
![linter status bar](http://i.imgur.com/7WDPPxZ.png)

**Comment by ctolkien** [comment]
We're already using that for the left and right labels:
https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/lib/completion-provider.ts#L76
