### ISSUE TITLE
Enums are showing up as methods in the autocomplete list

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#138]
![image](https://cloud.githubusercontent.com/assets/95136/7312486/e6b22ac6-e9ff-11e4-913b-698cf6f440be.png)

**Comment by nosami** [comment]
Hmm... this is most likely a bug in omnisharp-roslyn.

**Comment by nosami** [comment]
Fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/185

**Comment by david-driscoll** [comment]
When is the next push of the server binaries?

**Comment by nosami** [comment]
As soon as someone merged my PR :)

**Comment by nosami** [comment]
fixed in 0.4.1
