### ISSUE TITLE
Colorize log

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-atom#140]
Since we now have Stdio (#113, #119) we get better log information from the server such as the log type.  We could colorize the server log to capture error, warning, info, etc.

**Comment by adriaanp** [comment]
Will the color be base on the LogLevel property on the Body of the event?

**Comment by nosami** [comment]
Yes. Ideally, I think it should be the same as if you invoked the server from the terminal.

Info - white, Error - red, everything else - white.

**Comment by nosami** [comment]
Fixed in v0.4.4
