### ISSUE TITLE
Get CI up and running

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#144]
@willl did you want to take this one? I know you started making some progress, not sure how far you got.

**Comment by jmkelly** [comment]
If you want to test against linux, give us a yell, I can help setup on travis if needed.

**Comment by willl** [comment]
Yeah. Made some progress. Then nuked my fork. Was planning on tackling it
this weekend.


On Sat, Apr 25, 2015 at 12:57 PM, James Kelly <notifications@github.com>
wrote:

If you want to test against linux, give us a yell, I can help setup on
travis if needed.


--
Reply to this email directly or view it on GitHub
<https://github.com/OmniSharp/omnisharp-atom/issues/144#issuecomment-96122960>
.










-- 
Sent from MetroMail

**Comment by willl** [comment]
See #148 :)
