### ISSUE TITLE
'Toggle' doesn't actually toggle.

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#145]
It starts the server, but doesn't turn it off if you hit 'toggle' again.

**Comment by sgwill** [comment]
I think this is also related to #111, kill the klr threads when shutting down.

**Comment by ctolkien** [comment]
Think this is fixed in current master.

**Comment by sgwill** [comment]
Toggle now toggles. The #153 PR updates the status of the toggle.

**Comment by ctolkien** [comment]
@sgwill  - we can close this now yeah?

**Comment by sgwill** [comment]
Oh, yeah. Closing.
