### ISSUE TITLE
Libuv isn't found

### ISSUE THREAD

**Issue by jmkelly** [OmniSharp/omnisharp-atom#147]
![image](https://cloud.githubusercontent.com/assets/124026/7331180/bac0fe38-eb49-11e4-9deb-4fa7e572313d.png)

Running on xubuntu 14.04
sudo apt-get install libuv-dev already run, seems that libuv still can't be found when trying to fire up omnisharp.

Omnisharp-atom 0.4.1

**Comment by davidfowl** [comment]
This shound;t be required anymore since we're using stdio right?

**Comment by david-driscoll** [comment]
Atom isn't handing the server a port anymore, but it appears the server is still binding to a port.  I know I've seen this.

**Comment by nosami** [comment]
Eurgh. We need to fix that.

**Comment by nosami** [comment]
I checked this. It works fine without libuv installed with the latest version of omnisharp-atom.
