### ISSUE TITLE
Autocomplete broken in method parameters

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#150]
![image](https://cloud.githubusercontent.com/assets/95136/7332358/922890ac-eaf0-11e4-9efb-b366da692b93.png)

Typing the same thing within a method body works:

![image](https://cloud.githubusercontent.com/assets/95136/7332363/b890e7e4-eaf0-11e4-9458-406bda851ef3.png)

/cc @nosami 

Likely a bug in omnisharp-roslyn but discovered using atom.

**Comment by nosami** [comment]
Fixed in #154
