### ISSUE TITLE
Intellisense is too aggressive and often gets in the way of typing

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#152]
![aggressive_atom](https://cloud.githubusercontent.com/assets/95136/7332386/9c95ec32-eaf1-11e4-84cd-85d6617d3df5.gif)

**Comment by david-driscoll** [comment]
ahhh good ol' semicolon intellisense, lol.

**Comment by nosami** [comment]
Should be fixed by #154. If not, re-open. Thanks.
