### ISSUE TITLE
Build fails on travis-ci

### ISSUE THREAD

**Issue by jmkelly** [OmniSharp/omnisharp-atom#155]
https://travis-ci.org/OmniSharp/omnisharp-atom

**Comment by willl** [comment]
Yeah. The specs fail :(


On Sun, Apr 26, 2015 at 10:21 AM, James Kelly <notifications@github.com>
wrote:

https://travis-ci.org/OmniSharp/omnisharp-atom


--
Reply to this email directly or view it on GitHub
<https://github.com/OmniSharp/omnisharp-atom/issues/155>.










-- 
Sent from MetroMail

**Comment by ctolkien** [comment]
We need to either yank, or rewrite the tests/specs so they work - preferably the latter :) We've got CI working but false positive issues.

**Comment by willl** [comment]
Yeah, definitely better to get the specs working. In the meantime, we can
always just comment out the line that runs the specs until the specs are
fixed.

**Comment by jmkelly** [comment]
fixed in #162
