### ISSUE TITLE
/filesChanged end point broken

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#161]
![image](https://cloud.githubusercontent.com/assets/95136/7340691/f00d5920-ec47-11e4-99fb-1b58f9c7264e.png)

**Comment by nosami** [comment]
How odd... I'm sure I saw that working. It isn't now though /cc @sgwill

**Comment by sgwill** [comment]
Hmm, I'll take a look.

**Comment by sgwill** [comment]
Fixed in #166

**Comment by davidfowl** [comment]
Works!
