### ISSUE TITLE
Server fails to start: "Missing method ToList in assembly"

### ISSUE THREAD

**Issue by andersekdahl** [OmniSharp/omnisharp-atom#164]
Hi!
I may be doing this wrong, I just downloaded `omnisharp-atom` (0.4.3) in atom (already had the other dependencies) and when I try to start the server via `ctrl + alt + o` this is what I get in the `Omnisharp output` view:
![screenshot from 2015-04-27 13 00 24](https://cloud.githubusercontent.com/assets/163637/7346335/abf1b452-ecdd-11e4-84d2-287c7fb8f65d.png)

Am I supposed to have something else installed in order to use this plugin? Do I need Mono or Roslyn, or is that bundled with the plugin?

Sorry if this isn't enough information, I'd be glad to fill in the needed blanks.

I'm on Ubuntu 12.04, and Atom 0.190.0 if that helps.

**Comment by willl** [comment]
Hi @andersekdahl, yep, you'll definitely need to install Mono (v3.4.1 or higher).

**Comment by andersekdahl** [comment]
Thanks for the reply! I'll try to get a hold on mono >= 3.4.1 then, but that's easier said than done when you're stuck on Ubuntu 12.04.

**Comment by nosami** [comment]
These [instructions](http://www.mono-project.com/docs/getting-started/install/linux/) should work for you.

**Comment by andersekdahl** [comment]
Tried that, but that got me version 2.8. Also tried to build it but the build failed without telling me why.

Anyway, thanks for the help!

**Comment by nosami** [comment]
Did you see this note for 12.04? http://www.mono-project.com/docs/getting-started/install/linux/#older-ubuntu-releases-ubuntu-1210-and-1204
