### ISSUE TITLE
Diagnostics shows invalid error 'unexpected character'

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#165]
It's always the first character of the first line.

![screen shot 2015-04-27 at 14 15 54](https://cloud.githubusercontent.com/assets/667194/7348272/036c87c0-ece8-11e4-95fc-108f7fa0dba6.png)

This started happening since the switch to stdio.

**Comment by ctolkien** [comment]
Wasn't able to replicate this on Windows.

**Comment by awec** [comment]
Not repro for me on mac.

**Comment by willl** [comment]
Cloned MVC Samples from aspnet/mvc on OS X. Opened the file and could replicate this.

**Comment by david-driscoll** [comment]
It has to do with creating the buffer string to send it to the server.  I could not see in the atom side through the dev tools when I had an identical issue on windows when first getting stdio ready.

Once is serialized over the stdin it appeared on the server.  I was even able to debug into the server and see it.
