### ISSUE TITLE
Keybindings apply for all languages

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#173]
Some keybindings such as ctrl-alt-o probably need to work no matter what the language grammar of the editor file is. Most should only work for c# buffers.

**Comment by nosami** [comment]
Looking at other plugins, we should be able to do something like this `'atom-text-editor[data-grammar~=cs]':`. I can't seem to get it to work for omnisharp-atom though :(

**Comment by david-driscoll** [comment]
`atom-text-editor[data-grammar~="cs"]`  ?

**Comment by nosami** [comment]
so far I tried [data-grammar~=cs], [data-grammar~=csharp], [data-grammar~="cs"], [data-grammar~="csharp"], [data-grammer="source cs"] and [data-grammar="source csharp"]

**Comment by david-driscoll** [comment]
maybe it doesnt like ~=?

I have 

```
'atom-text-editor:not([mini])[data-grammar*="cs"]':
  'ctrl-k ctrl-d': 'omnisharp-atom:code-format'
```
in my custom keymaps and it works.

**Comment by nosami** [comment]
Hmm... tried that too.. not working. Starting to think this is something specific to my machine or OSX

**Comment by nosami** [comment]
As soon as I change it to `'atom-text-editor':`, the keys all start working again :(

**Comment by ctolkien** [comment]
I'll take a look at this this evening.

**Comment by ctolkien** [comment]
Sooo `'atom-text-editor:not([mini])[data-grammar~="cs"]':` works for me.
