### ISSUE TITLE
Send /filesChanged for project.lock.json files

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#179]
See https://github.com/OmniSharp/omnisharp-roslyn/issues/189

**Comment by adriaanp** [comment]
Why was this issue closed? Don't we need it anymore?

**Comment by willl** [comment]
@adriaanp It's closed because PR #186 fixes it (I think).

**Comment by davidfowl** [comment]
Its not

**Comment by nosami** [comment]
@adriaanp It was closed by accident when I closed #186 We still need a file watcher.
