### ISSUE TITLE
Test runner

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#18]

**Comment by david-driscoll** [comment]
What is the goal with this one?

**Comment by nosami** [comment]
I'd be happy for now if it could just take the test command and ran the command in an output window. 

Having clickable stack traces would be a bonus, as would any sort of gui.

**Comment by nosami** [comment]
Like this in emacs

![](https://raw.githubusercontent.com/OmniSharp/omnisharp-emacs/master/pics/tests.png)

**Comment by willl** [comment]
Closing, implemented in #411. For ASP.NET 5 apps anyway.
