### ISSUE TITLE
Space should dismiss auto complete

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#182]
![go_away_on_space](https://cloud.githubusercontent.com/assets/95136/7368524/8059563a-ed5d-11e4-86ed-52d13e2c7628.gif)

**Comment by david-driscoll** [comment]
This looks like it might be fixed with the latest auto complete changes.

**Comment by nosami** [comment]
fixed in https://github.com/OmniSharp/omnisharp-atom/pull/222
