### ISSUE TITLE
DNVM and Beta4 Support

### ISSUE THREAD

**Issue by jrock2004** [OmniSharp/omnisharp-atom#187]
Does this new plugin support the newly release beta4 version? If not where can I keep track so I know when it does?

**Comment by willl** [comment]
As far as I know, we're using beta 3 at the moment.

Beta 4 support will be a change to https://github.com/OmniSharp/omnisharp-roslyn, and then the omnisharp-server-roslyn-binaries also need to get updated.

**Comment by davidfowl** [comment]
It does supprt beta3 beta4 and and beta5
