### ISSUE TITLE
Add warning dots in the margins to match error dots

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#190]
Linter adds a Red dot in an error line. I want (an option) to see warning lines highlighted too.

Actually, same option should show warnings in the linter error pane, if the pane is enabled.

**Comment by ctolkien** [comment]
This is already supported?

Here's the trifecta (error, warning, info):

![image](https://cloud.githubusercontent.com/assets/515955/7407830/35b2a8a4-ef59-11e4-8536-d47cc88c6d53.png)

**Comment by sgwill** [comment]
Huh. That's exactly what I was thinking. I'm only showing error on my machine. I'll look at my setup again.

**Comment by sgwill** [comment]
You're right, it already works. I just needed to check this box in the linter settings.

![2015-04-30_1232](https://cloud.githubusercontent.com/assets/1507077/7417608/3234ecec-ef35-11e4-909f-b7c2ebfcab9f.png)

**Comment by ctolkien** [comment]
That screenshot indicates a bug either in linter or their docs - you should be getting warnings w/o that checked, but not 'info'.

**Comment by sgwill** [comment]
As it turns out, I didn't have warnings on my page, just info. I added a warning, without that box checked, and it worked. I think everything's in order.
