### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by novaterata** [OmniSharp/omnisharp-atom#191]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\critchea\AppData\Local\atom\app-0.194.0\resources\app.asar\src\atom.js:57:13)
Object.subscribeToEvents (C:\Users\critchea\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.coffee:56:12)
Object.activate (C:\Users\critchea\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.coffee:21:7)
Package.activateNow (C:\Users\critchea\AppData\Local\atom\app-0.194.0\resources\app.asar\src\package.js:222:19)
```

**Comment by willl** [comment]
Hi @novaterata, what version of omnisharp atom have you got installed?

I think you're using an older version.

**Comment by novaterata** [comment]
You're quite right. I had 0.2.1 installed. Atom did not update the package
for some reason, but it's going do now.
