### ISSUE TITLE
Compile TS instead of having Atom Compile it

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-atom#198]
This would allow us to use new features such as ES6 imports, destructuring and such.

It also may have a positive impact on start time, in regards to getting the package running.

**Comment by willl** [comment]
I wonder how much time we would truly end up saving?

**Comment by david-driscoll** [comment]
In start up, it depends on the compiler that atom is using.  With the ts 1.4 compiler, it's a decent amount of time.  With the ts 1.5 compiler (that `atom-typescript` uses) it would be very marginal.

I would also include developer productivity things, destructuring, `for of`, etc.

https://github.com/Microsoft/TypeScript/wiki/Roadmap#15

**Comment by david-driscoll** [comment]
Closing as we now have a gulp task to compile on demand, and compileOnSave set for those using atom-typecript.
