### ISSUE TITLE
Go to Implementation and Go To Definition aren't working

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#201]
Tried  master on both Mac and Windows. It's definitely going to server, and returning the right file(s), but we aren't navigating to the files, or in the case of multiple implementations, we aren't displaying them in the find window.

**Comment by sgwill** [comment]
`Find Usages` is the same problem: not showing in the find window

**Comment by sgwill** [comment]
This is still broken for me on mac, even after the PR

**Comment by nosami** [comment]
It works for me now with the fix. How are you starting Atom? With a folder via the command line? Are you using the auto-start mechanism?

**Comment by sgwill** [comment]
Ahh, I just recompiled the typescript and restarted, and now it's working. But, not on autostart, I had to toggle. This issue is closed for me.
