### ISSUE TITLE
Find Usages is not showing results

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#202]
Currently on Mac. Results are definitely coming back from the server, and the find pane is getting triggered, but no results are coming through

**Comment by david-driscoll** [comment]
I'm not seeing the problem, is anyone else seeing this issue?

**Comment by nosami** [comment]
Broken for me too. Only intellisense is working on master.

**Comment by sgwill** [comment]
This is still broken for me on mac, even after the PR

**Comment by sgwill** [comment]
Ahh, I just recompiled the typescript and restarted, and now it's working. But, not on autostart, I had to toggle. This issue is closed for me.
