### ISSUE TITLE
Question: Can we recompile TS on npm install?

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#205]
For those of us developing, occasionally fetching upstream and re-npm installing doesn't seem to always completely update. This is probably ignorance on my part. Can we force a recompile on npm install? @david-driscoll?

**Comment by nosami** [comment]
This was the reason for the tooltip PR not working for me too :)

**Comment by nosami** [comment]
I think I added a tooltip-view.ts previously and it was cached or something
somewhere.

**Comment by sgwill** [comment]
Yeah, seems that's it's *probably* just an issue for people working on omnisharp-atom, and not people installing from apm. Nevertheless, it'd be nice to have a more seamless, regular workflow.

**Comment by sgwill** [comment]
Oh, maybe this is related to #198

**Comment by david-driscoll** [comment]
Closing as we now have a gulp task to compile on demand, and compileOnSave set for those using atom-typecript.
