### ISSUE TITLE
Can't update omnisharp-atom if there's a running instance of omnisharp roslyn somewhere

### ISSUE THREAD

**Issue by willl** [OmniSharp/omnisharp-atom#212]
Okay, so I had 3 copies of Atom open, and one of them probably had omnisharp-atom running.

Got a notification that there was a package update available. Tried to update, but I'm getting an error.

EPERM, unlink 'C:\Users\xyz\.atom\packages\omnisharp-atom\node_modules\omnisharp-server-roslyn-binaries\lib\server\approot\packages\kre-clr-win-x86.1.0.0-beta3\bin\kre.clr.dll'

![image](https://cloud.githubusercontent.com/assets/926823/7486538/280e3534-f3ea-11e4-8f60-36ffe843c574.png)

The resolution is to open task manager and kill the various klr processes. Doing that, the update works.

**Comment by Astrophizz** [comment]
For me, this causes the package to become corrupt. Atom sees it, but can't update or uninstall it. I have to go into the .atom folder and delete it manually, then reinstall the package.

**Comment by willl** [comment]
The resolution for now, when you see that there is an update for omnisharp is to completely exit Atom.

Then, open up the command prompt/terminal and type `apm update omnisharp-atom`.

**Comment by ctolkien** [comment]
This isn't unique to us for what it's worth.

**Comment by david-driscoll** [comment]
We could listen to the update event, and try to kill all the servers.

**Comment by david-driscoll** [comment]
Hmmm we should be getting shut down according to...
https://github.com/atom/settings-view/blob/1e1619c1719f2623bcd21a0297fcc16ee2baf1c7/lib/package-manager.coffee#L203-L204

We should probably rebase https://github.com/OmniSharp/omnisharp-node-client/pull/3 and try it out.

**Comment by david-driscoll** [comment]
Maybe.... maybe this is fixed in #431
