### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-atom#230]
> yo@1.4.6 postinstall /private/var/folders/4g/0_hl8gsd007gdvqcjnl63kzh0000gn/T/apm-install-dir-11548-95769-13ppws4/node_modules/omnisharp-atom/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory

Everything looks all right!

> omnisharp-node-client@1.1.4 postinstall /private/var/folders/4g/0_hl8gsd007gdvqcjnl63kzh0000gn/T/apm-install-dir-11548-95769-13ppws4/node_modules/omnisharp-atom/node_modules/omnisharp-node-client
> gulp & tsd reinstall

[17:54:21] Using gulpfile /private/var/folders/4g/0_hl8gsd007gdvqcjnl63kzh0000gn/T/apm-install-dir-11548-95769-13ppws4/node_modules/omnisharp-atom/node_modules/omnisharp-node-client/gulpfile.js
[17:54:21] Starting 'default'...
[17:54:21] Finished 'default' after 10 ms

-> running reinstall

>> written 4 files:

    - chai/chai.d.ts
    - lodash/lodash.d.ts
    - mocha/mocha.d.ts
    - node/node.d.ts

> omnisharp-atom@0.4.14 postinstall /private/var/folders/4g/0_hl8gsd007gdvqcjnl63kzh0000gn/T/apm-install-dir-11548-95769-13ppws4/node_modules/omnisharp-atom
> tsd reinstall & grunt copy & grunt clean

>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-coffeelint" not found. Is it installed?
>> No "clean" targets found.
Warning: Task "clean" failed. Use --force to continue.

Aborted due to warnings.
>> Local Npm module "grunt-coffeelint" not found. Is it installed?
>> No "copy" targets found.
Warning: Task "copy" failed. Use --force to continue.

Aborted due to warnings.

npm WARN engine omnisharp-node-client@1.1.4: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.35","npm":"2.5.1"})
npm ERR! Darwin 14.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/yujunpeng/.atom/.apm/.apmrc" "--userconfig" "/Users/yujunpeng/.atom/.apmrc" "install" "/private/var/folders/4g/0_hl8gsd007gdvqcjnl63kzh0000gn/T/d-11548-95769-10s52zc/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! omnisharp-atom@0.4.14 postinstall: `tsd reinstall & grunt copy & grunt clean`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the omnisharp-atom@0.4.14 postinstall script 'tsd reinstall & grunt copy & grunt clean'.
npm ERR! This is most likely a problem with the omnisharp-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd reinstall & grunt copy & grunt clean
npm ERR! You can get their info via:
npm ERR!     npm owner ls omnisharp-atom
npm ERR! There is likely additional logging output above.

**Comment by jchannon** [comment]
Did you get this working? I have the same on OSX

**Comment by fishg** [comment]
@jchannon I have remove ~/.atom for testing ,still testing with slow network.

**Comment by fishg** [comment]
@jchannon I was successed by install follow module first:
 npm i -g grunt-cli grunt  gulp tsd

**Comment by jchannon** [comment]
theres been an update, should work now

**Comment by nosami** [comment]
fixed in v0.4.16

**Comment by fishg** [comment]
@jchannon @nosami Great.
