### ISSUE TITLE
Make find usages and error list keyboard friendly

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#251]
Right now, you need to use the mouse to select a reference to jump to.

I'd like it if we could navigate usages with the keyboard. Also we need keys to jump between the editor and the usages panel and back again.

I would prefer it if after running the find usages command, the usages pane automatically got the focus (ready for keyboard navigation)

The keys would need to be ran as commands so that they can be customised.

**Comment by david-driscoll** [comment]
Do I think we have find usages now, we just need the error list?

**Comment by nosami** [comment]
Find usages is a huge improvement on before, but I'd prefer it if navigation were done via commands instead. This way, the keys could be changed by the user.. vi keys for the win ;)

For error list, we need something similar... but again, I think these should be commands. It should be possible to navigate errors even without the panel being open.

**Comment by david-driscoll** [comment]
On it...!

**Comment by david-driscoll** [comment]
We don't have keybindings for the errors yet, but they can be bound by users if needed!
