### ISSUE TITLE
Flag for console.log / debug output?

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#261]
There's a lot getting dumped into the console output. Suggest we need to clean this up and/or perhaps have a 'Developer' value in the settings to turn these bits on as it's pretty handy to inspect what's coming back from the server.

Thoughts?

![image](https://cloud.githubusercontent.com/assets/515955/7626368/85552d12-fa4b-11e4-8dc4-1b938f83c39d.png)

**Comment by nosami** [comment]
yes!

**Comment by david-driscoll** [comment]
:+1:
