### ISSUE TITLE
Add command/ctrl enable hyperlink of valid symbols (ones under the mouse?) for go to definition

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#263]
This is an amazing feature and we should add it

**Comment by ctolkien** [comment]
This should just be a super simple keybinding yeah?

**Comment by willl** [comment]
Think the [code-links](https://github.com/AsaAyers/code-links) Atom package provides similar functionality to what is being proposed.

We could possibly use it like [coffee-links](https://github.com/AsaAyers/coffee-links) does, or just use it as inspiration for our own implementation :)
