### ISSUE TITLE
Auto start doesn't seem to work for me unless I open a .cs file

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#264]
Tried a few solutions (try omnisharp-roslyn) and it didnt auto start for some reason.

**Comment by sgwill** [comment]
It's not starting for me any longer either.

**Comment by sgwill** [comment]
I take it back. Latest from master worked just now.

**Comment by nosami** [comment]
It only works right now if you have a cs tab open on start. Otherwise, you need to open a cs tab before auto-start kicks in.

**Comment by david-driscoll** [comment]
We could potentially look at the open project it determine if its a "candidate" for project starting.

**Comment by nosami** [comment]
This seems to be working for me now even when a cs tab isn't visible on start. Close?

**Comment by davidfowl** [comment]
Works now
