### ISSUE TITLE
Show summary of errors and warnings in the status bar like vs code

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#265]
![image](https://cloud.githubusercontent.com/assets/95136/7630999/4c75f7b0-f9f1-11e4-976a-161580dd167d.png)

**Comment by sgwill** [comment]
This is added now. It's in version 0.4.29.

**Comment by ctolkien** [comment]
Note, we have a bit of double up now as the linter will also display warnings/errors in the statusbar (at least on the currently active editor), but this is all still way better overall! :+1:

**Comment by sgwill** [comment]
Yeah, can we turn off the linter status? Or, maybe, _should_ we turn of the linter statusbar?
