### ISSUE TITLE
Show detected projects (from omnisharp server) in status bar

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#266]
![image](https://cloud.githubusercontent.com/assets/95136/7631000/58a4afcc-f9f1-11e4-9a95-17b66df80711.png)

**Comment by david-driscoll** [comment]
@davidfowl @nosami how far down this rabbit hole do we want to go?

**Comment by nosami** [comment]
Not very IMO. The way atom works right now is quite different to the way @code works. 

The projects view in the screenshot relates to a single solution I believe, whereas we support multiple solutions simultaneously and transparently.

I find the change project option in @code to be quite confusing and completely unnecessary. The quick navigation to the project.json is fairly useful.

I think having project information could be useful for filtering diagnostics perhaps.. and also for selecting dnx commands (but we could just populate the command palette with all dnx commands for all projects - it's probably simpler all around)

**Comment by davidfowl** [comment]
Showing what projects were discovered is nice because the tree view doesn't reflect what projects were actually detected. That's the min bar I think.

**Comment by nosami** [comment]
I'm not saying we shouldn't display that, but what value does that provide to the end user? It sounds more like a debug tool :)

**Comment by david-driscoll** [comment]
We are all developers after all...

**Comment by nosami** [comment]
A debug tool for dnx ;)

**Comment by nosami** [comment]
I just don't see the point. If you click it, then what?

**Comment by david-driscoll** [comment]
Magic!

**Comment by david-driscoll** [comment]
![MAGIC](http://i907.photobucket.com/albums/ac276/Beowulf1990/mr-bean-magic.gif)

**Comment by david-driscoll** [comment]
This has been fixed!
