### ISSUE TITLE
Doc comments shouldn't be center aligned in tooltip

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#268]
![atom_center_aligned_doc_comments](https://cloud.githubusercontent.com/assets/95136/7631317/4903be60-f9f5-11e4-9d67-b457d38cefb8.gif)

**Comment by nosami** [comment]
![screen shot 2015-05-14 at 12 56 33](https://cloud.githubusercontent.com/assets/667194/7631347/c3f09e16-fa38-11e4-8e51-672b77a037cf.png)

Left aligned for me... anyone else?

**Comment by nosami** [comment]
Looks like this could be related to the theme that is installed. We should override the alignment.
