### ISSUE TITLE
node client throws on non c# projects

### ISSUE THREAD

**Issue by Mpdreamz** [OmniSharp/omnisharp-atom#281]
![image](https://cloud.githubusercontent.com/assets/245275/7655610/d838a566-fb24-11e4-9047-cedfdfc87fdc.png)

Investigating

**Comment by nosami** [comment]
@david-driscoll is also looking at this problem

**Comment by Mpdreamz** [comment]
just pushed a PR though :cry:

**Comment by david-driscoll** [comment]
It's two different problems, don't worry about it! :)
