### ISSUE TITLE
Grab a new gif for README

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#286]
Enough features have changed that we should have a new gif for README.

**Comment by ctolkien** [comment]
Who's got a nice high res screen to take this from? :)

**Comment by nosami** [comment]
![atomdemo](https://cloud.githubusercontent.com/assets/667194/7758038/8ad7bdfa-fffe-11e4-98be-74e0c660aabd.gif)

**Comment by willl** [comment]
@nosami Let's get that in :)

But wow, 44 deprecations?

**Comment by nosami** [comment]
Most of them are from the web browser plugin. None from omnisharp-atom :)

**Comment by nosami** [comment]
fixed by https://github.com/OmniSharp/omnisharp-atom/commit/4b849a053ee0e0788352c53adf270a0723db348f
