### ISSUE TITLE
[Tracking] Atom Dependency Checker updates

### ISSUE THREAD

**Issue by ctolkien** [OmniSharp/omnisharp-atom#288]
Ref: https://github.com/travs/atom-package-dependencies/pull/13

If / when this makes it in, we should flip back to using the official NPM version (as opposed to Basarat's fork), and handle the condition when APM does not install successfully.

**Comment by willl** [comment]
Looks like atom-typescript has moved to a different [NPM package](https://www.npmjs.com/package/atom-package-deps): https://github.com/TypeStrong/atom-typescript/pull/559

We should probably follow suit, as we were using the same implementation as they were previously using.

**Comment by k2b6s9j** [comment]
Not only has atom-typescript moved to that package, so have some of the Linter providers, allowing them to be installed by the user on their own.

If it's worth anything, this new package was made and is being maintained by AtomLinter team member @steelbrain.

**Comment by willl** [comment]
@k2b6s9j Cool. Our implementation of that was [_inspired_](https://github.com/OmniSharp/omnisharp-atom/pull/132) by atom-typescript. So probably not a bad idea for us to keep it that way.

Anyone who has the time for it is more than welcome to send a PR :)

**Comment by k2b6s9j** [comment]
I'll give it a shot tomorrow.

**Comment by david-driscoll** [comment]
:+1:
