### ISSUE TITLE
Code snippets get in the way

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#291]
![image](https://cloud.githubusercontent.com/assets/95136/7665092/3ee27ad4-fb5d-11e4-9668-027845972b65.png)

They are too global.

**Comment by nosami** [comment]
This is the same issue as this https://github.com/atom/autocomplete-plus/issues/465

**Comment by ctolkien** [comment]
Settings this to 3 (or potentially higher) should resolve it:
https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/lib/completion-provider.ts#L115

(My atom is asplode for now, so I can't test :boom: )
