### ISSUE TITLE
Global errors and warnings list doesn't show errors for both target frameworks

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#292]
I can specify multiple target frameworks in project.json and the server will handle return diagnostics for all of them. This doesn't seem to be working with the global errors window:

![image](https://cloud.githubusercontent.com/assets/95136/7665286/41f97864-fb65-11e4-9b69-2e6d81843e11.png)

The linter detects the diagostics but the global window does not.

**Comment by nosami** [comment]
This seems to be working for me.

**Comment by nosami** [comment]
The global errors endpoint is using the same code as the current buffer linter. 

Is it possible that you switched projects at some point? Because switching projects / having multiple projects open is a feature that was recently introduced.

**Comment by david-driscoll** [comment]
@davidfowl is this still a problem for you?
