### ISSUE TITLE
Linter too aggressive

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#313]
![image](https://cloud.githubusercontent.com/assets/95136/7696253/21679688-fdb0-11e4-99c4-fe21cbd7677a.png)

Feels like it gets in the way alot while typing.

**Comment by nosami** [comment]
I'm not sure if it's possible or not for us to fix this automatically, but you can fix it using the linter settings

![screen shot 2015-05-19 at 10 27 45](https://cloud.githubusercontent.com/assets/667194/7699719/dd53d68e-fe11-11e4-9c75-14aba3643f80.png)

**Comment by david-driscoll** [comment]
I don't know if there is much we can do here unless we write our own code that adds the appropriate markers and such.

Closing for now.
