### ISSUE TITLE
Intellisense for Named Parameters

### ISSUE THREAD

**Issue by brad-jones** [OmniSharp/omnisharp-atom#318]
Hi Guys,

Not sure if this is a feature request or a bug but as per the title, I was half expecting to get Intellisense for Named Parameters. For example refer to: http://stackoverflow.com/questions/4994637 The second answer clearly shows a screenshot of VS with the expected Intellisense drop down.

The linter does make reference to the named parameter, see this screenshot:
![image](https://cloud.githubusercontent.com/assets/2754772/7717897/4c2677b2-feec-11e4-9e90-799e10cebc3a.png)

But nothing appears in the Intellisense drop down when I start typing.

Cheers Brads

**Comment by nosami** [comment]
This is the same issue as #319

**Comment by david-driscoll** [comment]
Closing will track with #319
