### ISSUE TITLE
Disable autocomplete on ';'

### ISSUE THREAD

**Issue by eyamenko** [OmniSharp/omnisharp-atom#32]
Hello. Is it possible to disable autocomplete on ';' - typing? It's a bit annoying. Every time I wanna type in a ';' - symbol, suggestions list appears.

**Comment by willl** [comment]
Might be fixed (I think) when we move to the autocomplete-plus 2.0 API with #122.

**Comment by ctolkien** [comment]
This is fixed, but pretty sure not due to the 2.0 API changes, think it was one @nosami and https://github.com/OmniSharp/omnisharp-atom/commit/318a1d904a0d1a1f763ee56cda3e67c89ff0e81a
