### ISSUE TITLE
Can't toggle Omnisharp

### ISSUE THREAD

**Issue by adriaanp** [OmniSharp/omnisharp-atom#323]
Trying to attempt to "restart the server" toggling Omnisharp while auto started turns the flame icon off, but  not omnisharp. Still get intellisense and requests on the Omnisharp output window.

**Comment by david-driscoll** [comment]
@adriaanp try this again with the latest changes, I think @nosami said this should be fixed.

**Comment by adriaanp** [comment]
Yup this is fixed now.
