### ISSUE TITLE
Consider making Advanced New File a dependency

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#330]
Right now, if you press cmd-n to create a new file in Atom, the file has no filename. This means that we can't associate the file with any project/client which means things just aren't going to work until after the file has been saved.

Consider making this https://github.com/Trudko/advanced-new-file a package dependency. This forces the new file to have a filename before it's saved. 

Maybe hook into Atom's new file command and offer this dialog instead. Thoughts?

**Comment by david-driscoll** [comment]
I wonder if there is any hook to tell what directory the new file was *supposed* to be created under?  We could leverage that.

**Comment by nosami** [comment]
How would the editor even know that if you don't tell it?

**Comment by david-driscoll** [comment]
I dunno, the active folder, the new file event. 

I'm not sure if can or can't but might be worth looking into.

-----Original Message-----

**Comment by nosami** [comment]
It isn't even a cs file if it doesn't have an extension.

**Comment by david-driscoll** [comment]
This has been done!
