### ISSUE TITLE
Goto definition opens multiple editors

### ISSUE THREAD

**Issue by perbnielsen** [OmniSharp/omnisharp-atom#331]
When I choose "Omnisharp->Goto definition" more than one editor with the same file opens.

An way to reproduce it is to create a WebApplication via OmniSharp and then open AccountController.cs.
Select "Go to definition" on ApplicationUser and several editors with IdentityModels.cs opens.

I am on Atom 201 and Omnisharp 0.6.5 on a mac.

**Comment by nosami** [comment]
Not for me.

![atomissue331](https://cloud.githubusercontent.com/assets/667194/7784949/7571cff4-0171-11e5-83cd-5d27dc6b45c2.gif)

**Comment by perbnielsen** [comment]
I just had another look, and it does only open one window, but only the first time after starting Atom, After closing the IdentityModels.cs window and then doing "Go to definition" again the second one always opens more than one. I have seen two to five windows open at once.

**Comment by nosami** [comment]
![atomissue331b](https://cloud.githubusercontent.com/assets/667194/7785304/4a765d22-0182-11e5-93c8-258e29d798c2.gif)

**Comment by perbnielsen** [comment]
I have just reproduced it on a different mac which has not had Atom installed before by:

Downloading Atom.
Installing the Omnisharp-atom package
Installing Mono version 4.0.0
Opening the project I have posted here: https://dl.dropboxusercontent.com/u/19866522/Empty.zip
Opening the file Program.cs
Selecting Go to declaration on "Class1" on line 8 "Class1 foo;"
Closing the editor with Class1.cs
Selecting Go to declaration on "Class1" on line 8 "Class1 foo;"

I have uploaded a video of it, if that is of any help. By the way, what do you use to create those handy gif screen casts?
 https://dl.dropboxusercontent.com/u/19866522/AtomMultipleOpen.mov

**Comment by nosami** [comment]
OK. I've just seen this happen :) Something is badly wrong here. Will see if I can fix.

**Comment by nosami** [comment]
fixed in v0.6.6
