### ISSUE TITLE
Path too long

### ISSUE THREAD

**Issue by dracan** [OmniSharp/omnisharp-atom#332]
On Windows, in the Atom C:\users\<username>\.atom folder, by default there's a .gitignore file, which suggests that by design you should be able to commit your Atom settings / configuration to a Git repo to share across multiple devices.

Unfortunately after adding the omnisharp-atom package, I can no longer commit the .atom folder, as Git now fails saying that the omnisharp-atom paths are greater than the maximum length of 256 characters.

**Comment by nosami** [comment]
This doesn't seem to be the recommended way of backing things up. There are some suggestions here http://www.atomtips.com/how-to-synchronize-atom-between-computers/ though.

**Comment by dracan** [comment]
Works for me :)

**Comment by gamicklisafisher** [comment]
"Long Path Tool" did the trick for me.
