### ISSUE TITLE
omnisharp complaining List<String> could not be found.

### ISSUE THREAD

**Issue by txchen** [OmniSharp/omnisharp-atom#337]
Platform: MacOSX + atom + mono 3.12

Code:

```
using System;
using System.Collections.Generic;

namespace ClassLibrary
{
    public class Class1
    {
        public Class1()
        {
            var aaa = new List<String>(10);
        }
    }
}
```

Error:
The type or namespace name 'List<String>' Could not be found (are you missing a using directive or an assembly reference?)

The code can be compiled by dmcs.

**Comment by adriaanp** [comment]
If you do `new List<string>(10)` instead? (notice the lower case string)

**Comment by txchen** [comment]
@adriaanp  tried, same error.

BTW, my project.json:

```
{
    "version": "1.0.0-*",
    "dependencies": {
    },

    "frameworks": {
        "dnx451": {
            "dependencies": {}
        },
        "dnxcore50": {
            "dependencies": {
                "System.Runtime": "4.0.20-*"
            }
        }
    }
}
```

Created by omnisharp, I haven't touched it.

**Comment by AndersNS** [comment]
You need to reference System.Collections for dnxcore50

```javascript
{
    "version": "1.0.0-*",
    "dependencies": {},
    "commands": {
        "run": "run"
    },
    "frameworks": {
        "dnx451": {},
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-*",
                "System.Collections": "4.0.0-beta-*"
            }
        }
    }
}
```

**Comment by txchen** [comment]
@AndersNS cool, it works! BTW, where can I find which assembly contains which namespace, for dnxcore50?

**Comment by nosami** [comment]
@txchen look here http://packagesearch.azurewebsites.net/ for now

**Comment by AndersNS** [comment]
packagesearch.azurewebsites.net Is pretty useful

**Comment by nosami** [comment]
@AndersNS beat ya :)

**Comment by txchen** [comment]
Thanks everyone!
