### ISSUE TITLE
Can't type open bracket symbol (`{`)

### ISSUE THREAD

**Issue by thiago-negri** [OmniSharp/omnisharp-atom#340]
Anywhere in the system I can type the open bracket symbol (`{`), except when using omnisharp-atom.

It works if I editr other file types in Atom, but when I edit C# files using Atom with omnisharp-atom, I can't type it.

I press the key for the open bracket symbol and a closing bracket appears in the editor (`}`).

For example, I create a new file and type in:

```
namespace TNegri
// cursor is here
```

When I type `{`, this happens:

```
namespace TNegri
}//cursor is here
```

WHAT?

I'm using a brazilian portuguese keyboard (ABNT-2), so in order to type "open bracket symbol", I use the sequence `SHIFT+[`.

What is happening?

**Comment by nosami** [comment]
This looks like an atom bug combined with an OmniSharp bug.

The Brazilian keyboard layout has the { key where the } key is on UK and US keyboards.

![](https://jabbrlive.blob.core.windows.net/jabbr-uploads/clipboard_c884.png)

We capture the } key to do format block on keystroke. Will see if we can find a workaround.

**Comment by nosami** [comment]
Seems like a well known issue with Atom https://github.com/atom/atom-keymap/issues/37 

https://github.com/andischerer/atom-keyboard-localization might fix it.

**Comment by luisrudge** [comment]
This plugin + the config below made everything work just fine.

```json
{
    "81": {
        "alted": 47
    },
    "220": {
        "shifted": 125
    },
    "221": {
        "shifted": 123
    }
}
```

**Comment by david-driscoll** [comment]
Looks like this should be fixed, let us know if you need more help!

**Comment by luisrudge** [comment]
Yeah. I fixed installing this package: https://atom.io/packages/keyboard-localization
