### ISSUE TITLE
Doesn't work with the proposed beta4 server.

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#341]
With the proposed PR https://github.com/OmniSharp/omnisharp-roslyn/tree/origin/beta4, the server seems to launch correctly inside Atom. 

The log looks normal, but the green flame icon doesn't turn green and nothing works.

**Comment by david-driscoll** [comment]
I wasn't able to recreate this on windows (doesn't mean it isn't happening).

Any other steps to recreate, or should I just sit down my Ubuntu VM and figure it out?

**Comment by nosami** [comment]
@david-driscoll I haven't tried it on Windows yet.

This is definitely a server issue. If I run scripts/Omnisharp --stdio twice in two separate shells simultaneously, then the 2nd one shows

```
{"Event":"ProjectChanged","Body":{"MsBuildProject":null,"AspNet5Project":{"Path":"/Users/jason/src/omnisharp-roslyn/tests/OmniSharp.Stdio.Tests/project.json","Name":"OmniSharp.Stdio.Tests","Commands":{"test":"xunit.runner.aspnet"},"Configurations":["Debug","Release"],"ProjectSearchPaths":["/Users/jason/src/omnisharp-roslyn/tests","/Users/jason/src/omnisharp-roslyn/src"],"Frameworks":[],"GlobalJsonPath":"/Users/jason/src/omnisharp-roslyn/global.json","SourceFiles":null}},"Seq":24,"Type":"event"}
System.Exception: Error -48 EADDRINUSE address already in use
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check (Int32 statusCode) <0x1199e36e0 + 0x0005d> in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.listen (Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle handle, Int32 backlog, Microsoft.AspNet.Server.Kestrel.Networking.uv_connection_cb cb) <0x1199e6870 + 0x0006b> in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle.Listen (Int32 backlog, System.Action`4 callback, System.Object state) <0x1199e6630 + 0x0010f> in <filename unknown>:0
```
This shows that it's launching Kestrel even though we specified stdio.

The server doesn't send the {"event" : "started }, nor does it respond to requests. It only sends log messages and ProjectChanged/ProjectAdded events

**Comment by david-driscoll** [comment]
@nosami now that we fixed the issue in omnisharp-roslyn, should we close this ticket?

**Comment by nosami** [comment]
yeah!
