### ISSUE TITLE
Pressing F1 to see tooltips can show tooltips for different editors

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#343]
![screen shot 2015-05-28 at 03 25 35](https://cloud.githubusercontent.com/assets/667194/7851522/52c4b7b6-04e9-11e5-8f85-54323b401310.png)

**Comment by AndersNS** [comment]
I can only reproduce this if I have an active cursor in multiple editors. Are there any other scenarios?

**Comment by david-driscoll** [comment]
I see this with more than one active cursor in the same editor.

**Comment by david-driscoll** [comment]
This should be fixed, tooltips are now only bound to the editor that happens to be the one with the active cursor.
