### ISSUE TITLE
couldn't update omnisharp-atom within atom

### ISSUE THREAD

**Issue by joeizang** [OmniSharp/omnisharp-atom#349]
npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/joe/.atom/.apm/.apmrc" "--userconfig" "/home/joe/.atom/.apmrc" "install" "/tmp/d-115429-2405-bsj9j/package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for /tmp/npm-2477-0578354d/registry.npmjs.org/omnisharp-client/-/omnisharp-client-1.4.5.tgz
npm ERR! Expected: be0ca6e7ce3e510e6ba1d017d793b7597c4a5d46
npm ERR! Actual:   e7beb84286295b174949358824c01639a33557b5
npm ERR! From:     https://registry.npmjs.org/omnisharp-client/-/omnisharp-client-1.4.5.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115429-2405-1i7pkr4/npm-debug.log

Not sure if this issue was fixed.
Atom version is 0.201.0

**Comment by nosami** [comment]
Looks like a corrupt download.

**Comment by joeizang** [comment]
so I need to just try again? I did and every its the same. should I do a manual apm install omnisharp?

**Comment by nosami** [comment]
You could try... maybe something is cached somewhere.

```sh
rm -rf ~/.atom/packages/omnisharp-atom
apm install omnisharp-atom
```

**Comment by nosami** [comment]
You could try... maybe something is cached somewhere.

```sh
rm -rf ~/.atom/packages/omnisharp-atom
apm install omnisharp-atom
```

**Comment by joeizang** [comment]
ok lemme try this and thanks shirker...

**Comment by joeizang** [comment]
It installed successfully but I cannot start omnisharp as it says I have atom-yeoman version 0.2.0 and I need 0.3.0 and all attempts to upgrade fails silently as the package never updates...is this a bug or its just a small glitch somewhere...

**Comment by joeizang** [comment]
and I just checked I have atom-yeoman version 0.3.1 installed... :-)

**Comment by david-driscoll** [comment]
That's strange...

**Comment by joeizang** [comment]
just started atom to work and discovered that something fixed itself when I shutdown and started it this morning. so dunno what to make of that. Atom should have a log of all the happenings, can I check there for any expo on what happened? Thanks for all the good work
