### ISSUE TITLE
Auto completion inside a string literal

### ISSUE THREAD

**Issue by mat-mcloughlin** [OmniSharp/omnisharp-atom#355]
I'm assuming this isn't expected behaviour but atom attempts intellisense inside string literals and its coming back with a list of keywords

**Comment by nosami** [comment]
Will be fixed when the sever moves to csharpcompletionservice

**Comment by nosami** [comment]
fixed by https://github.com/OmniSharp/omnisharp-roslyn/pull/234

**Comment by nosami** [comment]
fixed in v0.12.2
