### ISSUE TITLE
Uncaught Could not find a client for location /Users/Martin/Projects/cSharp/test.cs

### ISSUE THREAD

**Issue by martinerk0** [OmniSharp/omnisharp-atom#356]
[Enter steps to reproduce below:]

1. crashed at the empty file

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.9.1

### Stack Trace

Uncaught Could not find a client for location /Users/Martin/Projects/cSharp/test.cs

```
At /Users/Martin/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

undefined
```

### Commands

```
     -0:01.5.0 application:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus",
      "autocomplete-snippets",
      "autocomplete-html",
      "autocomplete-css"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.1
autocomplete-haskell, v0.4.3
color-picker, v2.0.2
haskell-ghc-mod, v0.6.3
ide-haskell, v0.5.7
language-glsl, v2.0.0
language-haskell, v1.0.0
linter, v0.12.6
omnisharp-atom, v0.9.1

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Was there also a project file of some sort (csproj, project.json, global.json)?

Sounds like it might be correct result, but it shouldn't be raised as an error.

**Comment by martinerk0** [comment]
No, there was not, my bad, but I got another error and it crashed again when I tried to install this package manually.

**Comment by david-driscoll** [comment]
Closing for now, we have a few other issues we can track failures to start (and alerting the user properly)
