### ISSUE TITLE
Update to latest Linter API

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-atom#364]
https://github.com/AtomLinter/linter-plus/issues/29

**Comment by ctolkien** [comment]
I'll put my hand up for this one if noone else wants it.

**Comment by nosami** [comment]
I don't think the new linter API is ready yet anyway?

**Comment by steelbrain** [comment]
__Note:__ The new linter has replaced the old one and has been published.

**Comment by ctolkien** [comment]
Guess I'd better get busy then...

**Comment by nosami** [comment]
We need to decide what we are going to do about linter as it now shows errors by default.

![screen shot 2015-06-27 at 20 52 08](https://cloud.githubusercontent.com/assets/667194/8393606/bc8ce064-1d0e-11e5-9c22-605bc75c6a3b.png)

Should we use linter instead of our own error panel? This is the direction that atom-typescript is taking.

**Comment by ctolkien** [comment]
We've come full circle on this quite a few times. Initially we had our own error window prior to using the linter plugin. It was removed when we integrated with linter (as it didn't support global errors at the time), it was then added back in, as having global errors is super handy for .net.

My 2c, we should drop our own error window (again) and integrate with the new linter functionality. I would prefer not to have .net errors in one spot and all other errors in another spot. Broadly, I think we should take integration with the ecosystem vs going on our own even if it means we lose a feature or two.

Thoughts?

**Comment by nosami** [comment]
I think the difference now is that linter supports per solution as well as per file errors.

I'd be happy to just use the linter plugin errors.... but it can be a little annoying as it moves the rest of our panel up. Not sure if there's any solution to that.

**Comment by david-driscoll** [comment]
I'm fine with disabling/removing our own error window for now, but I think we should explore the possibility of "overriding" the linter behavior, perhaps through an extension of linter?  What about keybinds, does linter support keybinds, or should we keep our keybinds?

I myself also hate that it moves our window up, we lose so much screen space when there are a few errors, if the user also has the output/find window open.  (It also annoying moves the find and replace window when errors start going away).

Also another thing of note, if/when we move to event based diagnostics, will that integrate well with linter, do we have any idea?

**Comment by nosami** [comment]
Overriding linter behaviour via a config option sounds like the best idea to me. I've gotten quite fond of our own panel now that it supports keybindings.

I don't think that event based diagnostics would make any difference either way - we still control what they both show.

**Comment by ctolkien** [comment]
> I've gotten quite fond of our own panel now that it supports keybindings.

Is this not the sort of thing that could get added into core linter?

**Comment by nosami** [comment]
What if we could somehow make the linter errors show up within our panel?

**Comment by david-driscoll** [comment]
I see two choices.

1) We can see about getting a service (or something similar) added to linter, that lets us hide the linter features when an Omnisharp Editor is active.
2) We could force the linter elements to be hidden and stay hidden when an Omnisharp Editor is active. We still want the lint errors for the active editor to show up.

@nosami I'm sure we can add the linter errors to panel, if it would help.

Honestly I think the first option is worth a shot, we can always create a PR that adds the feature, to help it along.  Worst case, we get an answer of "no" :imp:

**Comment by steelbrain** [comment]
__Note:__ Linter has a new `linter:toggle` command that let's you enable/disable all the linters for the current text editor. How about when you show your own Omnisharp Editor, You toggle the linters for that editor. and when you feel like the user might need the linters again, toggle it again.

**Comment by steelbrain** [comment]
Also we tried to add some keybindings lately, but we're just like 3 or 4 people actively working on linter, so didn't have much ideas and ended up removing everything else except the peek keybinding. We would love to review a PR if it adds some convinient keybindings to the core linter.

**Comment by steelbrain** [comment]
Also, does C# support traces for errors? 'cause if it does, We support that in the latest linter
Ref: https://github.com/AtomLinter/Linter/issues/587#issuecomment-115070888

**Comment by david-driscoll** [comment]
@steelbrain thanks for the info!

We're just exploring our next steps, there's only a handful of us with time to work on omnisharp as well.

**Comment by Mpdreamz** [comment]
I think I was the most adement about sticking to our own error panel the last time around, linter sure has changed and just skimming their issues list shows that many of the reserves I had are tackled or have a PR pending. 

I do very strongly prefer our (multiline) formatting of the errors then the default in the linter output pane. Also our whole row is actionable. Maybe this is something we can push back to the linter project.

Right now panels stack, so the linter output and our various find (and other future) panels all get stacked which from a UI (no clear separation) and UX perspective kinda blows IMO. This to me is enough reason to run with the linter output panel disabled, even if we remove our output. It would be nice if atom tabbed panels docked at the bottom automatically. /cc @benogle (https://github.com/atom/atom/pull/3837)

**Comment by david-driscoll** [comment]
Done!

For now I've hidden the linter UI (only for our editors) but this is something we could address again if needed.

**Comment by steelbrain** [comment]
@Mpdreamz This behaviour is not yet documented yet, but if you set `multiLine:true` of some long messages, You'll have them wrapped by default and user will be able to expand them by clicking an arrow like icon.
