### ISSUE TITLE
Bring back the package restore notification....

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#365]
... cos it was kindda cool.

**Comment by david-driscoll** [comment]
Probably my fault?

-----Original Message-----

**Comment by nosami** [comment]
probably :laughing:

**Comment by david-driscoll** [comment]
:|

-----Original Message-----

**Comment by nosami** [comment]
We really ought to have some tests for this stuff.. I'll look into it when I get chance.

**Comment by david-driscoll** [comment]
We need a good automation story.

-----Original Message-----

**Comment by nosami** [comment]
fixed
