### ISSUE TITLE
Atom goes nuts

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#377]
![atom-goes-nuts](https://cloud.githubusercontent.com/assets/667194/8024009/9cdd841a-0d1b-11e5-9b81-4e02f3cb5ade.gif)

If you watch this gif, you can see that the number of unfulfilled requests spikes at 10. Sometimes it's 12 for me.

There should be at the very most 2 autocomplete requests during this sequence - 1 on pressing 't' and the other on '.'

I also think that we shouldn't be calling /getcodeactions at all when typing (maybe check to see if intellisense popup is visible). Same for /codecheck. We almost certainly don't want to be doing the solution wide check while typing.

I don't know why /updatebuffer is called during this sequence

**Comment by adriaanp** [comment]
/updatebuffer is called before a  solution wide analysis /codecheck, because the buffer does not get updated on the server when requesting with Filename = null
