### ISSUE TITLE
Specify the selection text range (when available) to code actions

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#382]
https://github.com/OmniSharp/omnisharp-roslyn/blob/c62d4a2dddbfd026ed61a5d8762ec538129190ab/src/OmniSharp/Models/CodeActionRequest.cs#L7-L10

This would allow us to do things like `Extract Method`

**Comment by david-driscoll** [comment]
@nosami don't we have this now?

**Comment by nosami** [comment]
yeah
