### ISSUE TITLE
Uncaught Could not find a client for location C:\Users\camypaper\OneDrive\Programming\gen.cs

### ISSUE THREAD

**Issue by Camypaper** [OmniSharp/omnisharp-atom#385]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Unknown Windows Version
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.12.5

### Stack Trace

Uncaught Could not find a client for location C:\Users\camypaper\OneDrive\Programming\gen.cs

```
At C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

undefined
```

### Commands

```
     -0:11.8.0 application:open-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "markdown-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.6
file-icons, v1.5.7
japanese-wrap, v0.2.10
linter, v0.12.7
markdown-preview-plus, v1.5.0
mathjax-wrapper, v0.1.0
omnisharp-atom, v0.12.5

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Was there a project.json or sln file in the directory?

We should try and cover this case with #433
