### ISSUE TITLE
Code Fix completions should appear next to the text where you invoke the command.

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#388]
Like this
![](https://cloud.githubusercontent.com/assets/874898/8124233/af482e1c-111b-11e5-96ba-17755b705c6b.gif)

from atom-typescript. We should totally copy it :)

**Comment by ctolkien** [comment]
noice :+1:

**Comment by ctolkien** [comment]
noice :+1:

**Comment by david-driscoll** [comment]
:+1:
