### ISSUE TITLE
keyboard shortcut display?

### ISSUE THREAD

**Issue by rakkarage** [OmniSharp/omnisharp-atom#39]
![1](https://cloud.githubusercontent.com/assets/962340/5099483/fdcb91d6-6f64-11e4-8a2b-965b602be662.png)

**Comment by david-driscoll** [comment]
Closing as per Jabbr, it's fixed for windows and *nix.

**Comment by ctolkien** [comment]
Reopening, not fixed for me?

![](http://i.imgur.com/dzuRc9V.png)

**Comment by david-driscoll** [comment]
hmmm, @ctolkien what os? just windows?  I wonder if it's a font thing maybe?

**Comment by ctolkien** [comment]
Yeah Windows, above was on Win10, this is on another machine (8.1)

![](http://i.imgur.com/jmQtbqn.png)

**Comment by willl** [comment]
Still an issue for me (on 8.1).

I think it depends on what fonts you've got installed. I think it should just grab whatever is set. I think right now it is hard coded in the following locations: 

* https://github.com/OmniSharp/omnisharp-atom/blob/66bd6550bf9115ac7977de33e8313ab72ec22515/lib/omnisharp-atom/views/omni-output-pane-view.ts#L25
* https://github.com/OmniSharp/omnisharp-atom/blob/83397fd557d9458705408240f45e41ac064d2f8a/lib/omnisharp-atom/views/find-pane-view.ts#L25

**Comment by ctolkien** [comment]
Note as well, that the build view doesn't display that message.

Am looking into this today.

**Comment by sgwill** [comment]
Can we close this for the same reason that we closed #159?

**Comment by nosami** [comment]
![screen shot 2015-05-16 at 03 20 45](https://cloud.githubusercontent.com/assets/667194/7664328/a8392b64-fb7a-11e4-9bec-4cb0c294d3b9.png) Looks like this on my Windows 7 vm

**Comment by sgwill** [comment]
What if we skip the damn symbols and just show `ctrl-alt-o`?

**Comment by ctolkien** [comment]
We did have a PR that loaded this from the keybindings... but we killed it... cos of auto-starting...

**Comment by david-driscoll** [comment]
@ctolkien @sgwill @nosami should we kill this one then too?
