### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-atom#400]
If omnisharp-atom start，cpu usage aways 10+% .Like MacBook battery killer.
![qq20150626-1](https://cloud.githubusercontent.com/assets/1423545/8371191/8c877b08-1c06-11e5-86d8-a4fa39a4fe83.png)

**Comment by nosami** [comment]
I can verify this. Even when Atom is idle, there is high cpu usage.

When I uninstall omnisharp-atom and restart, the cpu drops down to around 1%.

**Comment by nosami** [comment]
Fixed in v0.17.0
![screen shot 2015-06-26 at 20 53 18](https://cloud.githubusercontent.com/assets/667194/8386136/d75c6ec4-1c45-11e5-943a-489518803db9.png)

**Comment by fishg** [comment]
👍

**Comment by nosami** [comment]
Can we close this then?
