### ISSUE TITLE
Predefined type 'System.Object' is not defined or imported

### ISSUE THREAD

**Issue by NDavidBrown** [OmniSharp/omnisharp-atom#410]
I get this error message in C# (`.cs`) files within a project in Unity on a class name when I attempt to define a class.

I have the latest version of Mono installed, running on Windows 8.

Any ideas how I can overcome this basic error?!

**Comment by nosami** [comment]
Do you have dnvm installed? https://github.com/aspnet/Home

omnisharp-atom needs 1.0.0-beta4

**Comment by NDavidBrown** [comment]
I'll try that then post again, thank you.

I'm amazed neither the GitHub project homepage nor the main wiki page for this project mentions this requirement!

**Comment by nosami** [comment]
It's here https://github.com/OmniSharp/omnisharp-atom/wiki#runtime-prerequisites

Could be clearer though :)

**Comment by nosami** [comment]
Updated readme - https://github.com/OmniSharp/omnisharp-atom#runtime-prerequisites

**Comment by NDavidBrown** [comment]
Installing Visual Studio 2015 RC fixed the issue - thanks for the link :-)
