### ISSUE TITLE
Trigger server restart when git branch changes

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-atom#418]
Currently we don't have reload solution endpoint, but we should be able to tie into the atom git integration (somehow) and forcibly restart the current solution that the user is working on.

**Comment by nosami** [comment]
Cool... but the server will probably watch for file changes at some point too. Don't know how far away that is yet though - we were waiting for CoreCLR

**Comment by david-driscoll** [comment]
If we get the server checking for files we can close the ticket :)
