### ISSUE TITLE
Overlay API exploration

### ISSUE THREAD

**Issue by Mpdreamz** [OmniSharp/omnisharp-atom#43]
I've personally not invested a lot of time updating omnisharp-atom because all the cool features I wanted we're depending on being able to do overlays in the editor easy

The Atom folks added a pretty sweet API https://github.com/atom/atom/pull/4144 for all of this which landed in Atom 2 weeks ago so I/we (but mainly I :)) need to get my ass back in gear. 

- [X] Reimplement autocomplete using overlay API (see #44 )
- [x]  `alt+enter` refactorings, omnisharp allows you to get a list of available refactorings at current position, this should be smoother then relying on the command launcher (cmd+shift+p) which visually works better for global actions.

This issue serves as a scratchpad while we fletch out the basis for both.

**Comment by david-driscoll** [comment]
We have this now with the nice code actions window from @nosami !
