### ISSUE TITLE
Reimplement autocomplete using overlay API

### ISSUE THREAD

**Issue by Mpdreamz** [OmniSharp/omnisharp-atom#44]
We currently rely on `autocomplete-plus-async` which is a fork of a more popular package. 
We added it because we needed to be able to fetch completions in a non blocking fashion before the autocomplete window is drawn. 

It has the following issues:

- unmaintained package #40 
- bad default behavior (tab vs enter to select completions).
- autocompletions appear after ; #32 
- the autocomplete is ugly, no icons to disambiguate types and the preview is barely legible.

It does not appear async will be included in `autocomplete-plus` anytime soon:
https://github.com/atom-community/autocomplete-plus/pull/99

So we should explore drawing our own using the overlay api https://github.com/atom/atom/pull/4144

**Comment by Mpdreamz** [comment]
Closing this because of all the awesomeness that went into `autocomplete-plus` refactoring! :+1:

**Comment by donaldrivard** [comment]
Does code completion work in MM Atom? I cannot get code completion to work as it does in MM sublime.
