### ISSUE TITLE
cmd-d for go-to-definition is conflict with atom keybinding

### ISSUE THREAD

**Issue by axot** [OmniSharp/omnisharp-atom#441]
find-and-replace:select-next has same keybinding cmd-d.
Is there any method can change go-to-definition keybinding settings?

**Comment by david-driscoll** [comment]
@axot absolutely, you can edit `keymap.cson` under `~/.atom`

    '.platform-darwin atom-text-editor:not([mini])[data-grammar~="cs"], atom-text-editor:not([mini])[data-grammar~="csx"]':
      'cmd-d': 'unset!'

**Comment by axot** [comment]
@david-driscoll Thank you, it works!
