### ISSUE TITLE
Autocomplete not active despite Server being queried

### ISSUE THREAD

**Issue by tomwor** [OmniSharp/omnisharp-atom#442]
Autocompletion worked before, but sometime around updating to the latest version, it suddenly stopped. I can still see the server being queried though.

```
Starting OmniSharp server (pid:2302)
OmniSharp Location: [PATH]/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: [PATH]
Starting OmniSharp server (pid:2310)
OmniSharp Location: [PATH]/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: [PATH]
Omnisharp server running using stdio at location '[PATH]' on host 1977.
Using runtime '[PATH]/.dnx/runtimes/dnx-mono.1.0.0-beta5'.
Scanning '[PATH]' for DNX projects
No project.json based projects found
Could not determine solution file
Detecting CSX files in '[PATH]'.
Could not find any CSX files
Solution has finished loading
started
/projects: 200 99ms
/codecheck: 200 16ms
/v2/getcodeactions: 200 1ms
/v2/getcodeactions: 200 1ms
/codecheck: 200 0ms
/codecheck: 200 0ms
/updatebuffer: 200 2ms
/codecheck: 200 0ms
/v2/getcodeactions: 200 0ms
/v2/getcodeactions: 200 1ms
/typelookup: 200 0ms
```
Autocompletion is active and works with other languages.
Any ideas what it could be?

**Comment by david-driscoll** [comment]
Have you updated any of your keybindings locally?  (keymap.cson)

**Comment by tomwor** [comment]
I don't think so. 
I'm using the vanilla vim keybindings package though.

**Comment by david-driscoll** [comment]
does `ctrl-space` bring up auto complete for you?

**Comment by tomwor** [comment]
No, it doesn't.
Is there a way to query the server manually to see if there is a proper response?

**Comment by david-driscoll** [comment]
`clients[0]._client.autocomplete(clients[0]._client.makeRequest({}))` from dev tools should cause the server to attempt to auto complete (it might throw, but that's okay)

**Comment by nosami** [comment]
I've seen this behaviour when dnx 1.0.0-beta4 isn't installed.

**Comment by tomwor** [comment]
@nosami I do have dnvm installed, is there another dependency I'm missing?

**Comment by nosami** [comment]
does `dnvm list` show that 1.0.0-beta4 has the `default` alias?

**Comment by tomwor** [comment]
```
$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5          mono         ~/.dnx/runtimes      default
```

**Comment by nosami** [comment]
that'll be why it's not working then

**Comment by tomwor** [comment]
```
$ dnvm install 1.0.0-beta4
$ dnvm alias default 1.0.0-beta4

$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta4          mono         ~/.dnx/runtimes      default
       1.0.0-beta5          mono         ~/.dnx/runtimes
```

Unfortunately, it's still not working.
I'm on the latest omnisharp-atom 0.22.6.

**Comment by nosami** [comment]
@tomwor which plugins do you have installed?

**Comment by dhasenan** [comment]
I was experiencing the same problem, and then I realized I was on Atom 0.192 when 1.0.3 was already out. Have you updated to the latest Atom?

**Comment by tomwor** [comment]
#456 fixed it for me.
I removed all .sln files and recreated them through Unity. It's all working now.
Thanks for the great support guys!
