### ISSUE TITLE
Fails to start on single files.

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#447]
Tried starting Atom in am empty folder and creating a new .cs file.

I also tried closing Atom and restarting pointing at the .cs file directly.

**Comment by thecodejunkie** [comment]
:+1:

**Comment by david-driscoll** [comment]
I've added support for this in the unit testing branch, while the server starts, the lone cs file doesn't really do much by itself.

**Comment by david-driscoll** [comment]
Landed with the latest commit, might need some upstream work from omnisharp-roslyn, to start up against an empty file.
