### ISSUE TITLE
Use AtomLinter for syntax errors

### ISSUE THREAD

**Issue by park9140** [OmniSharp/omnisharp-atom#45]
You reimplement a large span of functionality provided by the AtomLinter/linter project.  You could provide a linter rather than implement your own management of syntax errors as you are doing.  I work on the project, and it would be great to get some additional input on how the linter can provide the necessary tooling to support your level of syntax errors and handling.  

If it seems like the linter project gives enough support for your current features I could drop a pull request with a linter to replace the existing duplicate functionality.

**Comment by ctolkien** [comment]
Dredging this issue back up. I do have a linter implementation in (https://github.com/OmniSharp/omnisharp-atom/commit/90dcab5ae2dee458aba8b88546930d8cf7841bf7)

My 2c, it removes some of the existing issues we have with bugs in the current system (e.g. #49), it removes a lot of code that we have duplicated. It syncs up with the rest of the ecosystems (e.g, errors for C# are not in a different spot to the rest of the errors for the rest of your project, error styling is consistent). Overall, is a better than what we have now.

Understand there are jitters if we're unable to then implement feature X, but we can always revive the current implementation if we need to.

If there is a more solid consensus, I'll clean up my implementation and fire off a PR.

**Comment by ctolkien** [comment]
Is resolved with #99
