### ISSUE TITLE
GoToDefinition opens files on line 1, and then navigates to the correct line

### ISSUE THREAD

**Issue by tmunro** [OmniSharp/omnisharp-atom#453]
This is mostly a problem for jump-list style tracking of the cursor position - e.g. with the [cursor-history package](https://github.com/t9md/atom-cursor-history). I believe changing [omni.ts's NavigateTo](https://github.com/OmniSharp/omnisharp-atom/blob/e4da78720bb05a213d4b2c0740a76e9fcef0e2ad/lib/omni-sharp-server/omni.ts#L87) to use the response line and column fixes this.

**Comment by nosami** [comment]
Ah! been looking for something like the cursor-history package. I miss ctrl-o and ctrl-i from vim :)
