### ISSUE TITLE
Navigate Back

### ISSUE THREAD

**Issue by Claytonious** [OmniSharp/omnisharp-atom#458]
After you CMD-click on a symbol to navigate to it, we need some way to navigate BACK to where we were. Is there some existing binding already for this that I'm not aware of?

Thanks!

**Comment by nosami** [comment]
There are a couple of atom plugins that provide this functionality. Not at
my computer right now to look for links!

**Comment by david-driscoll** [comment]
Someone had mentioned https://atom.io/packages/cursor-history earlier, take a look at that.
