### ISSUE TITLE
Using `csharp` alias for Markdown code triggers OmniSharp error checks

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/omnisharp-atom#459]
I'm writing README.md using GitHub version of Markdown - within a C# project - so OmniSharp is running, and as soon as I use `csharp` alias for code the OmniSharp triggers error checking against markdown document:
![20150801210736](https://cloud.githubusercontent.com/assets/14539/9023227/fc6e3026-3892-11e5-8930-a62d8c5c72fc.jpg)
This requires me to restart Atom to get rid of these errors.
Can I somehow help with this?
v.0.23.0
Atom: 1.0.3
Thanks!

**Comment by david-driscoll** [comment]
Is this project available anywhere to look at?  That's really weird... it sounds like it might be related to the grammar somehow, but I'm not 100% sure on that.

**Comment by peterblazejewicz** [comment]
using generator:
```
yo aspnet

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |   marvellous ASP.NET 5   |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What type of application do you want to create? Empty Application
? What's the name of your ASP.NET application? EmptyApplication
   create EmptyApplication/.gitignore
   ...
➜  development  cd EmptyApplication 
➜  EmptyApplication  ls
Startup.cs   hosting.ini  project.json wwwroot
➜  EmptyApplication  atom .
➜  EmptyApplication  touch README.md
```
README.md
```markdown
# README

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Description

```csharp

```

It's enough that I type `csharp` and press return key, it trigger syntax detection for C#:

![csharp](https://cloud.githubusercontent.com/assets/14539/9183769/9fbf31ba-3fb1-11e5-9e20-0d7882262767.gif)

updated to 0.23.1

**Comment by david-driscoll** [comment]
I'm seeing it now.... it has to do with the linter and it trying to (for
whatever reason) lint the code inside the csharp block of the markdown...
Thats cool.... confusing, but cool.

I'll work on a fix for it, thanks for the extra steps!

2015-08-10 16:48 GMT-04:00 Peter Blazejewicz <notifications@github.com>:

**Comment by peterblazejewicz** [comment]
@david-driscoll 
Tested with 0.23.2 - fixed. 
:bow: 
Thanks!
