### ISSUE TITLE
Use omnisharp without a solution file

### ISSUE THREAD

**Issue by nomatics** [OmniSharp/omnisharp-atom#461]

**Comment by david-driscoll** [comment]
So I've added support that will be merged in fairly soon.

How would you manage things like references and building in a scenario without a solution file or project file?  Wouldn't something like `.csx` be better suited for this?

**Comment by david-driscoll** [comment]
This has dropped with the latest version, but it seems omnisharp-roslyn doesn't have full support for it at the moment.
