### ISSUE TITLE
Tooltips not closing properly.

### ISSUE THREAD

**Issue by brad-jones** [OmniSharp/omnisharp-atom#471]
As per screenshot.

![image](https://cloud.githubusercontent.com/assets/2754772/9374255/5cf139ae-4737-11e5-876b-5efffe52f4a9.png)

Just updated to v0.24 and now sometimes, not all the time, tooltips will get left behind.
Closing the tab they belong to does not remove them. I guess because they are higher in the DOM structure. Only way to remove them is to close and re open atom.

The new reference counters look good though :)

**Comment by brad-jones** [comment]
No js errors appear in the Console.

**Comment by david-driscoll** [comment]
I've seen that before... I agree it's annoying... I'll look at fixing it
this weekend.

**Comment by david-driscoll** [comment]
@brad-jones Are you still seeing the tooltip problems?  I think I might have snuck a fix in for this, but didn't attach it to the issue.

**Comment by brad-jones** [comment]
Ah no, I haven't noticed the issue for a while now. Just updating to 0.24.13 right now.
If I see any more orphaned tool tips I'll re open the issue.
