### ISSUE TITLE
Include v0.24's new Reference Counters in the "Enhanced Highlighting" option.

### ISSUE THREAD

**Issue by brad-jones** [OmniSharp/omnisharp-atom#472]
I just updated to v0.24, already posted a bug with the tooltips #471 but also commented on how awesome the new Reference Counters are, I have already changed my mind...

Firstly just so we all know what I am talking about, these are the little guys I am referring to.
![image](https://cloud.githubusercontent.com/assets/2754772/9374508/1a578528-473a-11e5-8248-955d675459b4.png)

The issue is that now there are a millions of requests sent to ```/findusages```.
These requests make Atom unusable _(on my work pc at least)_.
![image](https://cloud.githubusercontent.com/assets/2754772/9374535/5efbe872-473a-11e5-9e4d-fe5fd3770eae.png)

> Those Reference Counters need a slightly lower Z-Index too I suspect :)

Either the massive number of ```/findusages``` requests is a bug in it's self. Or it would be good to include the new Reference Counters under the _"Enhanced Highlighting"_ option.
![image](https://cloud.githubusercontent.com/assets/2754772/9374590/d9ced50a-473a-11e5-8e1d-08639795f1d6.png)

That way it can easily be enabled / disabled.

A while ago I sent through this PR https://github.com/OmniSharp/omnisharp-roslyn/pull/274
I have since noticed that on my Home PC, dnx apps (hence omnisharp) compile and start in nano seconds (well very fast anyway). While my Work PC, dnx is a lot slower.

> FYI: On my work pc I did find that disabling Windows Defender made a huge difference to the compile and startup time of any dnx app. In general I think it's just a memory thing. Atom and DNX / Omnisharp seem to like lots of it.

My Home PC, has 8 Cores of Extreme i7 overclocked awesomeness, 16GB of RAM, a NVIDIA GTX 960 (my heater lol) and a couple of SSD's striped together. _Okay now I am just bragging :)_

On the other hand my Work Pc is only an i5 with 4GB of RAM.

My point I am trying to make is that anything like these new Reference Counters that have the potential to have a performance hit should have the option to enable and disable the feature.

Or do you all think I should just ask the boss for a new pc lol

**Comment by nosami** [comment]
Yeah, there should be an option for this. Also, it should only find references for methods that are currently visible on the screen.

**Comment by david-driscoll** [comment]
First, definitely ask your boss for a new  PC :smile:

So the z-index issue is actually a known bug in atom with the overlay decorator, there's no fix as of yet, I cleaned it up a little bit, so that they are constrained by the editor height, looks like it could use a little bit more tlc (perhaps include the dock height if its open).

I can add a feature flag for showing the fields so it can be disabled.  As for adjusting it to only find usages as they scroll into view, I have an idea how that would work, I just need to explore it.

**Comment by david-driscoll** [comment]
This wasn't actually fixed yet :sheep:

**Comment by david-driscoll** [comment]
This will land with #480

**Comment by david-driscoll** [comment]
@brad-jones code lens now only queries for usages if the lens item is to be shown, which depending on the file can vary.
