### ISSUE TITLE
Reference Counters - Shows `1` for itself

### ISSUE THREAD

**Issue by brendanjerwin** [OmniSharp/omnisharp-atom#474]
The Reference Counters feature would be a bit nicer if it didn't bother with itself. 

The values of `1` are just useless and clutter up the display. It'd probably be better if the self-references did nothing, and the _actual_ references had a count value of `total-1`. The general expectation for that is "how many times is this used?", not "how many times does it appear?".

**Comment by nosami** [comment]
I remember looking at Visual Studio to see how CodeLens counts references. It also counts itself.
