### ISSUE TITLE
Option to turn code lens off?

### ISSUE THREAD

**Issue by tomarus** [OmniSharp/omnisharp-atom#477]
Hello,

I really like the new code lens feature. However, it's not for me. It's in the way. It's annoying to look at. I'm sorry :)

It would be great if there would be a settings option to toggle this.

Thanks!

**Comment by lenstr** [comment]
+1, it would be really great to have that option

**Comment by david-driscoll** [comment]
This will be coming with #474 via #476

**Comment by tomarus** [comment]
The new option works as advertised. Thanks a lot guys!
