### ISSUE TITLE
How can I remove the footer? 

### ISSUE THREAD

**Issue by Camypaper** [OmniSharp/omnisharp-atom#479]
Hello omnisharp-atom team.
I uninstalled omnisharp-atom.
However, the footer(I don't know how to call it) remains now.

like this
[File 0 | Project 0 ] No Issues

How can I remove this?

**Comment by willl** [comment]
@Camypaper What you're referring to is actually coming from the Atom linter package. So you'll need to remove that too.

**Comment by Camypaper** [comment]
@willl Thanks:)
