### ISSUE TITLE
autocomplete is wrong the first time that you press '.'

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#484]
In this gif I press '.' and you can see wrong results. Then I press ctrl-space and the correct results appear. Deleting and typing '.' again returns the correct results too.
![autocomplete](https://cloud.githubusercontent.com/assets/667194/9585596/ebffff46-500f-11e5-8c57-bb82dd066030.gif)

**Comment by david-driscoll** [comment]
Is it strictly the first time _ever_ or just the first time for a field?

I've not been seeing this, but I will be on the lookout.

**Comment by david-driscoll** [comment]
sounds like via Jabbr this is working now.
