### ISSUE TITLE
dnx.exe could not be spawned

### ISSUE THREAD

**Issue by logikaljay** [OmniSharp/omnisharp-atom#486]
Hi Team,

Firstly, Loving the work so far!

However, When I try to run a new "Web Application" I get the following:
![image](https://cloud.githubusercontent.com/assets/980149/9619811/b511adf0-5167-11e5-842a-0a7634411687.png)

Not sure why it is searching for dnx.exe instead of dnx.
dnx is in my PATH and is found when typing `which dnx`:
![image](https://cloud.githubusercontent.com/assets/980149/9619852/05b3b15e-5168-11e5-80d7-122dbc772a7d.png)

Fresh install of omnisharp-atom on OSX 10.10

Any suggestions? Have I missed a step somewhere?

**Comment by david-driscoll** [comment]
@logikaljay do you happen to have mono installed?  I believe the version required is 4.1? Someone else can correct me if I'm wrong.

**Comment by logikaljay** [comment]
I do have mono installed, however it is version 4.0.2:
![image](https://cloud.githubusercontent.com/assets/980149/9623351/7693efa8-5193-11e5-8aff-87bd320b8d91.png)

**Comment by willl** [comment]
Could you please try following these instructions to verify your installation? http://docs.asp.net/en/latest/getting-started/installing-on-mac.html#verifying-your-installation

**Comment by willl** [comment]
Welp. Looks like I'm able to replicate this issue in my local OS X environment.

My guess is that there is something wrong in the win32 platform detection code:
https://github.com/OmniSharp/omnisharp-atom/blob/6ec80593d62ff74678c4de3ff365b9ed0e1e9e5f/lib/omnisharp-atom/features/command-runner.ts#L11

When I run `!(process.platform === "win32");` in the Atom/Chrome dev tools on my Mac it reports true, and on my Windows machine it says false.

And you can see on [line 161](https://github.com/OmniSharp/omnisharp-atom/blob/6ec80593d62ff74678c4de3ff365b9ed0e1e9e5f/lib/omnisharp-atom/features/command-runner.ts#L161)
`.map(solution => solution.model.dnx.RuntimePath + (win32 ? '/bin/dnx.exe' : '/bin/dnx'))`

So on Windows it'll use `/bin/dnx` and on OS X/Linux it'll use `/bin/dnx.exe`.

**Comment by david-driscoll** [comment]
oh wow... I fee like an idiot, I was debugging an issue some someone else
and that change shouldn't have made it in.  (I was testing what it should
look like on the mac side, but I only have windows machines).

That'll be an easy fix, and I'll add a unit test for it too.

Sorry for the inconvenience!

**Comment by david-driscoll** [comment]
I got a fix going into master now, assuming it passes travis I'll publish it.

**Comment by david-driscoll** [comment]
published and tagged, let us know if it's still a problem.

**Comment by logikaljay** [comment]
Thats no problem @david-driscoll!, thanks for all of your help and prompt replies
