### ISSUE TITLE
Omnisharp doesn't re-check consistently

### ISSUE THREAD

**Issue by TheOddler** [OmniSharp/omnisharp-atom#49]
I've noticed that for some reason omnisharp doesn't recheck consistently. It'll start rechecking when I type, and find a bunch of faults (because I haven't finished yet) and report those, but once I'm finished it'll continue showing the errors.

It's quite inconsistent in when it happens. The best way to get the error I found is by making a new method:

    void test() {
        return 5;
    }

this gives the error that I can't convert System.Int32 to System.Void. If I then *select the whole method* and delete it, the error stays without Omnisharp rechecking the code.

Note: I've only just started using Omnisharp in atom so I'll report back if I find more of a pattern in this. I'm on OSX 10.8.5, atom 0.170.0

**Comment by ctolkien** [comment]
The underlying issue is when there are no errors in an editor, then they aren't cleared from the error response. Few different ways to tackle this, discussing moving to the atom linter plugin.

**Comment by ctolkien** [comment]
Fixed!
