### ISSUE TITLE
Support for .cake extensions

### ISSUE THREAD

**Issue by patriksvensson** [OmniSharp/omnisharp-atom#496]
Since Atom have [Cake (C# Make)](http://cakebuild.net) support in the C# language bindings for `.cake` files since v0.7.0, I was wondering if there would be any interest in adding Omnisharp support for this file extension as well (Cake scripts are a superset of C#, that's the reason for it's own extension).

Would be awesome to use Omnisharp for this, and I can have a PR ready for this in no time :smile:

**Comment by willl** [comment]
Hi Patrik, I think someone else has started looking at this previously. Right now we're looking at getting plugin support added to the omnisharp-roslyn server first, check out this thread: https://github.com/OmniSharp/omnisharp-roslyn/issues/208

Keep an eye on that thread, and the related PR which @david-driscoll linked to and started.

**Comment by patriksvensson** [comment]
Will do! Thanks!
