### ISSUE TITLE
Omnisharp pane should be togglable

### ISSUE THREAD

**Issue by NullVoxPopuli** [OmniSharp/omnisharp-atom#505]
It takes up a lot of valuable screen space

![image](https://cloud.githubusercontent.com/assets/199018/9790162/77da8da8-57a2-11e5-9a74-2d878da4b4ea.png)

This is different from the error pane that is toggleable:

![image](https://cloud.githubusercontent.com/assets/199018/9790206/acd9785c-57a2-11e5-813d-5b3855d0aac8.png)

**Comment by nosami** [comment]
That is a config item in the linter package

<img width="380" alt="2015-09-10_1501" src="https://cloud.githubusercontent.com/assets/667194/9790268/00f4d056-57cd-11e5-9b60-6628dbdb208d.png">
