### ISSUE TITLE
choose dnx version

### ISSUE THREAD

**Issue by itajaja** [OmniSharp/omnisharp-atom#507]
this package requires dnx 1.0.0-beta5, but now there is already beta7. Is there a way to select the dnx to use?

**Comment by david-driscoll** [comment]
The dnx version that ships OmniSharp shouldn't cause any problems with anyone wanting to develop against beta7 and greater.

If there is a specific error you're seeing, we can help you diagnose that and see whats going on.

**Comment by itajaja** [comment]
oh. You are right, my bad. It was trying to load the dnx version specified in the global.json file... my bad.

**Comment by david-driscoll** [comment]
No worries!  Let us know if you have any other problems you need help with! :+1:
