### ISSUE TITLE
omnisharp-roslyn

### ISSUE THREAD

**Issue by luisrudge** [OmniSharp/omnisharp-atom#51]
Hey! Is someone looking at https://github.com/OmniSharp/omnisharp-roslyn to see what they're doing? Any thoughts on upgrading?

**Comment by Mpdreamz** [comment]
Aye, I disconnected from my laptop during the holiday seasons and have been swamped during january but I am looking to get back into getting on atom integration on par with the others again :)

Omnisharp v2 is the way forward so I'll look at integrating that first.

**Comment by luisrudge** [comment]
Great! Let me know if you need help!

**Comment by ctolkien** [comment]
Nearly there...

![screenie](https://s3.amazonaws.com/uploads.hipchat.com/41246/277076/hgRLO4TrJDPgi0H/upload.png)

**Comment by Mpdreamz** [comment]
:+1:

**Comment by ctolkien** [comment]
Released!
