### ISSUE TITLE
Failed at the omnisharp-atom@0.24.10 postinstall script 'gulp npm-postinstall'

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/omnisharp-atom#511]
Just a note: 
I had a problem on my Windows 8.1 machine @ work with recent OmniSharp plugin updates. Trying to update to 0.24.10 I've found that on my machine this commit changes:
https://github.com/OmniSharp/omnisharp-atom/commit/35e78b9a31804ee04c60fa46a505e8e73202d1b7
does fail to execute either via Atom or via apm, with normal and elevated level.
```
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! omnisharp-atom@0.24.10 postinstall: `gulp npm-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the omnisharp-atom@0.24.10 postinstall script 'gulp npm-posti
nstall'.
npm ERR! This is most likely a problem with the omnisharp-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp npm-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls omnisharp-atom
npm ERR! There is likely additional logging output above.
```

I had to install Gulp globally (`npm install -g gulp`) to work around a problem and update installation.
Thanks!

**Comment by david-driscoll** [comment]
@peterblazejewicz very strange... because that commit has been in place forever, were you on a really really old version?

**Comment by peterblazejewicz** [comment]
I have OmniSharp plugin installed at work machine from some time - I've noticed it has been failing recently (a month or so, maybe two) to install updates (and Atom is jerky about updates). So I just started to dig a problem.
The only thing I'm sure about this machine is that I had go install Gulp with `-g` flag. That's machine at my work (and Windows OS) so I'm not really know its guts frankly

**Comment by david-driscoll** [comment]
Fair enough, that's just odd because the current version targets the local
command in `node_modules/.bin` so the global shouldn't be needed anymore.

**Comment by peterblazejewicz** [comment]
@david-driscoll 
We can close this. I've made it as reference if someone hits similar problem.
Thanks!

**Comment by breiter** [comment]
I am having a problem with omnisharp-atom updating in Atom 1.2.4. I decided to uninstall the package and install it again. It just never completes in the Atom UI. I did `apm install omnisharp-atom --verbose` and it downloads everything and fails at the postinstall running gulp.

```
> omnisharp-atom@0.26.1 postinstall C:\Users\breiter\AppData\Local\Temp\apm-install-dir-115113-9716-mqap7o\node_modules\omnisharp-atom
> gulp npm-postinstall

'gulp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\breiter\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\breiter\\.atom\\.apmrc" "install" "C:\\Users\\breiter\\AppData\\Local\\Temp\\d-115113-9716-1u2fp8o\\package.tgz" "--target=0.34.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! omnisharp-atom@0.26.1 postinstall: `gulp npm-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the omnisharp-atom@0.26.1 postinstall script 'gulp npm-postinstall'.
npm ERR! This is most likely a problem with the omnisharp-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp npm-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls omnisharp-atom
npm ERR! There is likely additional logging output above.
failed
```

**Comment by breiter** [comment]
It also eventually fails to install in the UI: 

```
> omnisharp-atom@0.26.1 postinstall C:\Users\breiter\AppData\Local\Temp\apm-install-dir-115113-4816-1b9f0q1\node_modules\omnisharp-atom
> gulp npm-postinstall


npm WARN engine omnisharp-client@3.1.16: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN engine escodegen@1.7.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
'gulp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\breiter\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\breiter\\.atom\\.apmrc" "install" "C:\\Users\\breiter\\AppData\\Local\\Temp\\d-115113-4816-cz3awd\\package.tgz" "--target=0.34.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! omnisharp-atom@0.26.1 postinstall: `gulp npm-postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the omnisharp-atom@0.26.1 postinstall script 'gulp npm-postinstall'.
npm ERR! This is most likely a problem with the omnisharp-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp npm-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls omnisharp-atom
npm ERR! There is likely additional logging output above.
```

**Comment by david-driscoll** [comment]
Strange it should be using the locally installed copy. I'll look at this
today, i have an idea of how to get around the issue.
On Thu, Dec 3, 2015 at 7:09 AM Brian Reiter <notifications@github.com>
wrote:

> It also eventually fails to install in the UI:
>
> > omnisharp-atom@0.26.1 postinstall C:\Users\breiter\AppData\Local\Temp\apm-install-dir-115113-4816-1b9f0q1\node_modules\omnisharp-atom
> > gulp npm-postinstall
>
>
> npm WARN engine omnisharp-client@3.1.16: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
> npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
> npm WARN engine escodegen@1.7.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
> 'gulp' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\breiter\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\breiter\\.atom\\.apmrc" "install" "C:\\Users\\breiter\\AppData\\Local\\Temp\\d-115113-4816-cz3awd\\package.tgz" "--target=0.34.0" "--arch=ia32" "--msvs_version=2013"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
>
> npm ERR! omnisharp-atom@0.26.1 postinstall: `gulp npm-postinstall`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the omnisharp-atom@0.26.1 postinstall script 'gulp npm-postinstall'.
> npm ERR! This is most likely a problem with the omnisharp-atom package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp npm-postinstall
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls omnisharp-atom
> npm ERR! There is likely additional logging output above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OmniSharp/omnisharp-atom/issues/511#issuecomment-161615573>
> .
>
-- 
Thanks,
David

**Comment by david-driscoll** [comment]
The other thing I see is your node version is 0.10 that's fairly old, I
wonder if updating it would help?

On Thu, Dec 3, 2015 at 7:22 AM David Driscoll <david.driscoll@gmail.com>
wrote:

> Strange it should be using the locally installed copy. I'll look at this
> today, i have an idea of how to get around the issue.
> On Thu, Dec 3, 2015 at 7:09 AM Brian Reiter <notifications@github.com>
> wrote:
>
>> It also eventually fails to install in the UI:
>>
>> > omnisharp-atom@0.26.1 postinstall C:\Users\breiter\AppData\Local\Temp\apm-install-dir-115113-4816-1b9f0q1\node_modules\omnisharp-atom
>> > gulp npm-postinstall
>>
>>
>> npm WARN engine omnisharp-client@3.1.16: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
>> npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
>> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
>> npm WARN engine escodegen@1.7.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
>> 'gulp' is not recognized as an internal or external command,
>> operable program or batch file.
>> npm ERR! Windows_NT 6.2.9200
>> npm ERR! argv "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\breiter\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\breiter\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\breiter\\.atom\\.apmrc" "install" "C:\\Users\\breiter\\AppData\\Local\\Temp\\d-115113-4816-cz3awd\\package.tgz" "--target=0.34.0" "--arch=ia32" "--msvs_version=2013"
>> npm ERR! node v0.10.40
>> npm ERR! npm  v2.13.3
>> npm ERR! code ELIFECYCLE
>>
>> npm ERR! omnisharp-atom@0.26.1 postinstall: `gulp npm-postinstall`
>> npm ERR! Exit status 1
>> npm ERR!
>> npm ERR! Failed at the omnisharp-atom@0.26.1 postinstall script 'gulp npm-postinstall'.
>> npm ERR! This is most likely a problem with the omnisharp-atom package,
>> npm ERR! not with npm itself.
>> npm ERR! Tell the author that this fails on your system:
>> npm ERR!     gulp npm-postinstall
>> npm ERR! You can get their info via:
>> npm ERR!     npm owner ls omnisharp-atom
>> npm ERR! There is likely additional logging output above.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OmniSharp/omnisharp-atom/issues/511#issuecomment-161615573>
>> .
>>
> --
> Thanks,
> David
>
-- 
Thanks,
David

**Comment by breiter** [comment]
@david-driscoll Wow. That never even occurred to me. I assumed node was node bundled inside of Atom.

The global nodejs was for building Kudu but we're using 4.2 now, so I can try updating that.

**Comment by breiter** [comment]
@david-driscoll FYI. It is also broken when I removed my ~/.atom directory.

**Comment by breiter** [comment]
@david-driscoll My global node installation is actually 4.0.0 so the 0.10 version is coming from within the Atom 1.2.4 package.

```
PS> C:\users\breiter\AppData\Local\atom\app-1.2.4\resources\app\apm\bin\node.exe --version
v0.10.40
```

**Comment by david-driscoll** [comment]
Very weird I thought atom was on some much later version...
On Thu, Dec 3, 2015 at 7:31 AM Brian Reiter <notifications@github.com>
wrote:

> @david-driscoll <https://github.com/david-driscoll> My global node
> installation is actually 4.0.0 so the 0.10 version is coming from within
> the Atom 1.2.4 package.
>
> PS> C:\users\breiter\AppData\Local\atom\app-1.2.4\resources\app\apm\bin\node.exe --version
> v0.10.40
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OmniSharp/omnisharp-atom/issues/511#issuecomment-161620827>
> .
>
-- 
Thanks,
David

**Comment by david-driscoll** [comment]
As a temporary fix does installing gulp globally fix it?
On Thu, Dec 3, 2015 at 7:34 AM David Driscoll <david.driscoll@gmail.com>
wrote:

> Very weird I thought atom was on some much later version...
> On Thu, Dec 3, 2015 at 7:31 AM Brian Reiter <notifications@github.com>
> wrote:
>
>> @david-driscoll <https://github.com/david-driscoll> My global node
>> installation is actually 4.0.0 so the 0.10 version is coming from within
>> the Atom 1.2.4 package.
>>
>> PS> C:\users\breiter\AppData\Local\atom\app-1.2.4\resources\app\apm\bin\node.exe --version
>> v0.10.40
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OmniSharp/omnisharp-atom/issues/511#issuecomment-161620827>
>> .
>>
> --
> Thanks,
> David
>
-- 
Thanks,
David

**Comment by breiter** [comment]
It appears that `apm` bundles its own version of node which must be separate from what is part of electron. It is the same version on both OS X and Windows. Omnisharp-atom updated ok on OS X, though.

## OS X
```
find /Applications/Atom.app/ -iname node -exec {} --version \;
v0.10.40
```

## Windows
```
find ~/AppData/Local/atom -iname node\.exe -exec {} --version \;
v0.10.40
```

Also gulp appears to exist in ~/.atom on both but the install fails on Windows.

## OS X
```
$ find ~/.atom -iname gulp
/Users/breiter/.atom/.apm/gulp
/Users/breiter/.atom/.apm/registry.npmjs.org/gulp
/Users/breiter/.atom/packages/atom-yeoman/node_modules/.bin/gulp
/Users/breiter/.atom/packages/atom-yeoman/node_modules/gulp
/Users/breiter/.atom/packages/json-schema/node_modules/.bin/gulp
/Users/breiter/.atom/packages/json-schema/node_modules/gulp
/Users/breiter/.atom/packages/omnisharp-atom/node_modules/.bin/gulp
/Users/breiter/.atom/packages/omnisharp-atom/node_modules/gulp
```

## Windows
```
find ~/.atom/ -iname gulp
/c/Users/breiter/.atom/.apm/gulp
/c/Users/breiter/.atom/.apm/registry.npmjs.org/gulp
/c/Users/breiter/.atom/packages/atom-yeoman/node_modules/.bin/gulp
/c/Users/breiter/.atom/packages/atom-yeoman/node_modules/gulp
/c/Users/breiter/.atom/packages/json-schema/node_modules/.bin/gulp
/c/Users/breiter/.atom/packages/json-schema/node_modules/gulp
```

**Comment by breiter** [comment]
Yup. Maybe with the environment of `apm` doesn't have the path to where the local copy `gulp` actually exists?

```
> omnisharp-atom@0.26.1 postinstall C:\Users\breiter\AppData\Local\Temp\apm-install-dir-115113-9360-7x7wti\node_modules\omnisharp-atom
> gulp npm-postinstall

[12:44:45] Using gulpfile C:\Users\breiter\AppData\Local\Temp\apm-install-dir-115113-9360-7x7wti\node_modules\omnisharp-atom\gulpfile.js
[12:44:45] Starting 'clean:lib'...
[12:44:45] Starting 'clean:spec'...
[12:44:45] Finished 'clean:lib' after 36 ms
[12:44:45] Finished 'clean:spec' after 37 ms
[12:44:45] Starting 'clean'...
[12:44:45] Finished 'clean' after 4.76 μs
[12:44:45] Starting 'typescript'...
[12:44:46] Writing lib\omnisharp-atom.js
[12:44:50] Writing spec\omnisharp-atom-spec.js
[12:44:50] Writing lib\omnisharp.js
[12:44:50] Writing spec\test-helpers.js
[12:44:50] Writing spec\test-runner.js
[12:44:50] Writing lib\atom\command-runner.js
[12:44:50] Writing lib\atom\dock.js
[12:44:51] Writing spec\atom\dock-spec.js
[12:44:51] Writing lib\atom\feature-buttons.js
[12:44:51] Writing spec\atom\framework-selector-spec.js
[12:44:51] Writing lib\atom\framework-selector.js
[12:44:51] Writing spec\atom\solution-information-spec.js
[12:44:51] Writing lib\atom\generator-aspnet.js
[12:44:51] Writing spec\atom\status-bar-spec.js
[12:44:51] Writing lib\atom\menu.js
[12:44:51] Writing spec\atom\update-project-spec.js
[12:44:51] Writing lib\atom\server-information.js
[12:44:51] Writing spec\features\code-format-spec.js
[12:44:51] Writing lib\atom\settings-button.js
[12:44:52] Writing spec\features\code-lens-spec.js
[12:44:52] Writing lib\atom\solution-information.js
[12:44:52] Writing spec\features\command-runner-spec.js
[12:44:52] Writing lib\atom\status-bar.js
[12:44:52] Writing spec\features\find-symbols-spec.js
[12:44:52] Writing lib\atom\update-projects.js
[12:44:52] Writing spec\features\find-usages-spec.js
[12:44:52] Writing spec\features\go-to-definition-spec.js
[12:44:52] Writing lib\features\code-action.js
[12:44:53] Writing lib\features\code-check.js
[12:44:53] Writing spec\features\highlight-spec.js
[12:44:53] Writing lib\features\code-format.js
[12:44:53] Writing spec\features\intellisense-spec.js
[12:44:53] Writing lib\features\code-lens.js
[12:44:53] Writing spec\features\log-spec.js
[12:44:53] Writing spec\features\lookup-spec.js
[12:44:53] Writing lib\features\find-symbols.js
[12:44:53] Writing spec\features\navigate-up-down-spec.js
[12:44:53] Writing lib\features\find-usages.js
[12:44:54] Writing spec\features\package-restore-spec.js
[12:44:54] Writing lib\features\go-to-definition.js
[12:44:54] Writing spec\features\project-lock-spec.js
[12:44:54] Writing lib\features\highlight.js
[12:44:55] Writing spec\features\rename-spec.js
[12:44:55] Writing lib\features\intellisense.js
[12:44:55] Writing spec\features\run-tests-spec.js
[12:44:55] Writing lib\features\lookup.js
[12:44:55] Writing spec\features\server-information-spec.js
[12:44:55] Writing lib\features\navigate-up-down.js
[12:44:55] Writing spec\features\signature-help-spec.js
[12:44:55] Writing lib\features\notification-handler.js
[12:44:55] Writing lib\features\package-restore.js
[12:44:55] Writing spec\server\solution-manager-spec.js
[12:44:55] Writing lib\features\project-lock.js
[12:44:56] Writing lib\features\reload-workspace.js
[12:44:56] Writing lib\features\rename.js
[12:44:56] Writing lib\features\run-tests.js
[12:44:56] Writing lib\features\signature-help.js
[12:44:56] Writing lib\server\atom-projects.js
[12:44:56] Writing lib\server\composite-solution.js
[12:44:56] Writing lib\server\omni.js
[12:44:57] Writing lib\server\omnisharp-configuration.js
[12:44:57] Writing lib\server\project-view-model.js
[12:44:57] Writing lib\server\solution-manager.js
[12:44:58] Writing lib\server\solution.js
[12:44:58] Writing lib\server\view-model.js
[12:44:58] Writing lib\services\apply-changes.js
[12:44:58] Writing lib\services\completion-provider.js
[12:44:58] Writing lib\services\framework-provider.js
[12:44:58] Writing lib\services\linter-provider.js
[12:44:59] Writing lib\services\omni-select-list-view.js
[12:44:59] Writing lib\services\project-provider.js
[12:44:59] Writing lib\views\build-output-pane-view.js
[12:44:59] Writing lib\views\code-actions-view.js
[12:44:59] Writing lib\views\codecheck-output-pane-view.js
[12:44:59] Writing lib\views\command-output-window.js
[12:44:59] Writing lib\views\dock-window.js
[12:44:59] Writing lib\views\find-pane-view.js
[12:44:59] Writing lib\views\find-symbols-view.js
[12:44:59] Writing lib\views\framework-selector-view.js
[12:44:59] Writing lib\views\generic-list-view.js
[12:44:59] Writing lib\views\highlight-element.js
[12:44:59] Writing lib\views\omni-output-pane-view.js
[12:45:00] Writing lib\views\react-client-component.js
[12:45:00] Writing lib\views\rename-view.js
[12:45:00] Writing lib\views\signature-help-view.js
[12:45:00] Writing lib\views\solution-status-view.js
[12:45:00] Writing lib\views\status-bar-view.js
[12:45:00] Writing lib\views\test-results-window.js
[12:45:00] Writing lib\views\tooltip-view.js
[12:45:01] Finished 'typescript' after 16 s
[12:45:01] Starting 'npm-postinstall'...
[12:45:01] Finished 'npm-postinstall' after 5.13 μs
omnisharp-atom@0.26.1 node_modules\omnisharp-atom
├── escape-html@1.0.3
├── fuzzaldrin@2.1.0
├── fastdom@0.8.6
├── semver@5.1.0
├── bluebird@3.0.6
├── atom-package-deps@3.0.6 (sb-callsite@1.0.1)
├── ansi-to-html@0.3.0 (entities@1.1.1)
├── merge-stream@1.0.0 (readable-stream@2.0.4)
├── chai@3.4.1 (assertion-error@1.0.1, type-detect@1.0.0, deep-eql@0.1.3)
├── through2@2.0.0 (xtend@4.0.1, readable-stream@2.0.4)
├── globby@4.0.0 (arrify@1.0.0, object-assign@4.0.1, pify@2.3.0, array-union@1.0.1, pinkie-promise@2.0.0)
├── font-awesome@4.5.0
├── mocha-unfunk-reporter@0.4.0 (jsesc@0.4.3, ministyle@0.1.4, unfunk-diff@0.0.2, miniwrite@0.1.4)
├── fs-plus@2.8.1 (rimraf@2.2.8, mkdirp@0.3.5, async@0.2.10, underscore-plus@1.6.6)
├── glob@6.0.1 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
├── del@2.1.0 (is-path-cwd@1.0.0, object-assign@4.0.1, pify@2.3.0, pinkie-promise@2.0.0, is-path-in-cwd@1.0.0, globby@3.0.1)
├── rimraf@2.4.4 (glob@5.0.15)
├── jquery@2.1.4
├── mocha@2.3.4 (escape-string-regexp@1.0.2, supports-color@1.2.0, growl@1.8.1, commander@2.3.0, diff@1.4.0, debug@2.2.0, mkdirp@0.5.0, glob@3.2.3, jade@0.26.3)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, gulplog@1.0.0, chalk@1.1.1, lodash.template@3.6.2, multipipe@0.1.2, dateformat@1.0.12)
├── gulp@3.9.0 (interpret@0.6.6, pretty-hrtime@1.0.1, deprecated@0.0.1, archy@1.0.0, minimist@1.2.0, tildify@1.1.2, v8flags@2.0.10, semver@4.3.6, chalk@1.1.1, orchestrator@0.3.7, liftoff@2.2.0, vinyl-fs@0.3.14)
├── gulp-tslint@4.1.0 (map-stream@0.1.0, through@2.3.8, rcloader@0.1.4)
├── lodash@3.10.1
├── babel-plugin-transform-es2015-modules-commonjs@6.2.0 (babel-plugin-transform-strict-mode@6.2.0, babel-template@6.3.0, babel-types@6.3.0, babel-runtime@5.8.34)
├── tsd@0.6.5 (assertion-error@1.0.0, deep-freeze@0.0.1, type-detect@0.1.2, joi-assert@0.0.3, diff@1.4.0, open@0.0.5, rimraf@2.2.8, jsesc@0.5.0, lru-cache@2.5.2, ministyle@0.1.4, colors@1.1.2, uuid@2.0.1, minimist@1.2.0, minitable@0.0.4, exit@0.1.2, chalk@1.1.1, detect-indent@0.2.0, json-pointer@0.2.2, miniwrite@0.1.4, minimatch@1.0.0, mkdirp@0.5.1, event-stream@3.1.7, semver@4.3.6, uri-templates@0.1.9, glob@4.5.3, bl@0.9.4, universal-analytics@0.3.9, definition-header@0.1.0, bluebird@1.2.4, lazy.js@0.3.2, update-notifier@0.2.2, request@2.67.0, verror@1.4.0, joi@4.9.0)
├── babel-preset-stage-3@6.1.18 (babel-plugin-transform-async-to-generator@6.3.0, babel-plugin-transform-exponentiation-operator@6.1.18)
├── babel-preset-es2015@6.1.18 (babel-plugin-transform-es2015-shorthand-properties@6.1.18, babel-plugin-transform-es2015-block-scoped-functions@6.1.18, babel-plugin-check-es2015-constants@6.2.0, babel-plugin-transform-es2015-for-of@6.1.18, babel-plugin-transform-es2015-typeof-symbol@6.1.18, babel-plugin-transform-es2015-destructuring@6.1.18, babel-plugin-transform-es2015-literals@6.1.18, babel-plugin-transform-es2015-arrow-functions@6.1.18, babel-plugin-transform-es2015-template-literals@6.1.18, babel-plugin-transform-es2015-spread@6.1.18, babel-plugin-transform-es2015-function-name@6.1.18, babel-plugin-transform-es2015-sticky-regex@6.1.18, babel-plugin-transform-es2015-unicode-regex@6.1.18, babel-plugin-transform-es2015-computed-properties@6.1.18, babel-plugin-transform-es2015-object-super@6.1.18, babel-plugin-transform-es2015-parameters@6.1.18, babel-plugin-transform-es2015-block-scoping@6.1.18, babel-plugin-transform-es2015-classes@6.2.2, babel-plugin-transform-regenerator@6.2.0)
├── gulp-babel@6.1.1 (object-assign@4.0.1, replace-ext@0.0.1, vinyl-sourcemaps-apply@0.2.0, babel-core@6.2.1)
├── event-kit@1.4.1 (grim@1.5.0)
├── atom-space-pen-views@2.1.0 (space-pen@5.1.1)
├── generator-aspnet@0.0.91 (vs_projectname@1.0.2, uuid@2.0.1, chalk@1.1.1, yosay@1.1.0, findup-sync@0.3.0, yeoman-generator@0.19.2)
├── rx@4.0.7
├── typescript@1.7.3
├── ntypescript@1.201512030612.1
├── react@0.14.3 (envify@3.4.0, fbjs@0.3.2)
├── tslint@3.1.1 (underscore.string@3.1.1, optimist@0.6.1, findup-sync@0.2.1)
└── omnisharp-client@3.1.16 (strip-bom@2.0.0, md5@2.0.0, yargs@3.30.0)

done
```

**Comment by jwjames83** [comment]
Ran into this problem as well, except my problem was I had installed Node (chakra) to do some Windows 10 IoT. Removed that and all went well.

Probably different, but thought I'd share.

**Comment by sulhome** [comment]
I have this problem on Ubuntu 14.04. I have Node 5 installed. I have installed gulp globally but that **didn't fix the problem for me**
