### ISSUE TITLE
dnx beta detection, truthiness check in lodash._any()

### ISSUE THREAD

**Issue by rambocoder** [OmniSharp/omnisharp-atom#513]
Unless I change this line https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/command-runner.ts#L178 to be an explicit return true or false, using beta7 and beta8, the . gets added to the command to execute. 

`
if (any(['beta3', 'beta4', 'beta5', 'beta6'], x => runtime.indexOf(x) > -1)) {
`

The runtime.indexOf(x) > -1 will evaluate to true or false instead of -1 which lodash seems to think is truthy?

**Comment by david-driscoll** [comment]
willing to do a quick PR?

I can give you a quick rundown of how to setup your dev environment if you need.

**Comment by david-driscoll** [comment]
Published to `apm` as `v0.24.11`
