### ISSUE TITLE
Atom indents current line and next after semicolon

### ISSUE THREAD

**Issue by thomaswormann** [OmniSharp/omnisharp-atom#515]
Hi,
there is a really strange autocompletion happening in omnisharp-atom when I enter a semicolon.
The current line and the next one always get indented.
Any ideas?
Cheers,
Thomas

**Comment by nosami** [comment]
Auto indent and format for the current line or block happens on `;` and `}` keys.

**Comment by thomaswormann** [comment]
Oops, my bad.
I got confused by the fact that the default indentation seems to be two tabs not one.
Is there a way to change that? I'd rather use a single tab.

**Comment by nosami** [comment]
Unfortunately, I believe that it's not possible to auto format using tabs from the omnisharp-roslyn side. 4 spaces is ubiquitous though :)

I think your best bet would be to disable the `;` and `}` key binds in your own keymap.cson

```
'atom-text-editor:not([mini])[data-grammar~="cs"], atom-text-editor:not([mini])[data-grammar~="csx"]':
  ';': 'unset!'
  '}': 'unset!'
```

**Comment by nosami** [comment]
And you can change the default tab settings here in Atom settings

<img width="807" alt="screen shot 2015-09-23 at 21 40 18" src="https://cloud.githubusercontent.com/assets/667194/10058145/d4b4dcd8-623b-11e5-8fe9-0881ad70d8c7.png">

**Comment by thomaswormann** [comment]
Argh, of course. It's set to "soft-tabs" so it's indeed set to four spaces like you say and the tab setting in the default atom settings fixes that I have to hit tab twice to enter those 4 spaces.
Guess I'm a little tired today, thanks for helping me out with this! :)
