### ISSUE TITLE
Enabling "Enhanced Highlighting" causes atom to hang

### ISSUE THREAD

**Issue by adamralph** [OmniSharp/omnisharp-atom#531]
Initial Repro:

* Open a .cs file
* Enable Enhanced Highlighting
* Atom hangs

Further Repro:
* Kill atom from task manager
* Reopen atom
* Open a .cs file
* Atom hangs

Remedial action:
* Kill atom from task manager
* Reopen atom
* Disable Enhanced Highlighting
* Open a .cs file
* Atom does not hang

**Comment by david-driscoll** [comment]
Is the repo available to test against?  ( Highlighting has some fun edge cases :cry: )

**Comment by adamralph** [comment]
Yep, it's here https://github.com/ParticularLabs/Uranium

I was opening `src/Uranium.Console/Program.cs`.

**Comment by goodmorningcmdr** [comment]
Happens to me as well, though only on certain files. Some could simply be a single class with no functions and still crash. Tried adamralph's repo and not a single file crashed for me, yet an empty one on my end did.

**Comment by david-driscoll** [comment]
I've made a monkey patch (well enhanced highlighting is just a bug monkey patch anyway) but the editor should no longer lock up when enhanced highlighting is turned on.  It is possible that some enhanced bits, or normal highlighting bits might work incorrectly.  If they do let me know, but for now it shouldn't break the editor any longer.

I haven't noticed anything specifically, but that doesn't mean it can't happen.

**Comment by adamralph** [comment]
@david-driscoll :+1: it does indeed seem to be fixed
