### ISSUE TITLE
Go To Definition Annoyance

### ISSUE THREAD

**Issue by brad-jones** [OmniSharp/omnisharp-atom#532]
This feature / bug has been giving me the absolute shits for a while now.

The go-to-definition feature allows you to "ctrl-click" on a variable, method, type, etc.
And then it takes you to where it is defined, it's a great feature.

But the annoying part is that I always seem to activate it when I attempt to Copy and Paste. ie: "ctrl-c".

What often happens is that I copy the implementation and end up pasting it in front of it's definition, often in some other file. Sometimes though it's in the same file and on occasion this has gone unnoticed until all of a sudden a bunch of linter errors popup.

I think the issue stems from the fact that out of habit I tend to hold down the ctrl key, start selecting the text I wish to copy and then pressing "c", once I have finished selecting. Maybe my habits are unique, maybe not...

Anyway my quick fix for now is to just comment out the following:

```js
.where(e => /*e.ctrlKey ||*/ e.metaKey)
```

https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/go-to-definition.ts#L40

What does "metaKey" map to?

**Comment by nosami** [comment]
metaKay is the 'cmd' key on OS X. Not sure if it has any mapping on Windows.

**Comment by brad-jones** [comment]
Lol, my quick hack just stopped the underlining, it still actually navigates.

**Comment by david-driscoll** [comment]
In our defense, that's how Resharper behaves too (unless it has a delay, which is possible I guess, I haven't used it in a while).

I can add a feature flag around it though, shouldn't be a huge problem.

**Comment by brad-jones** [comment]
Is there another key we can us?
Maybe Alt?

**Comment by brad-jones** [comment]
I just changed the key to Alt, seems to be working fine.

Oh and also needed to change:
https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/go-to-definition.ts#L80
