### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by CrazyD0G** [OmniSharp/omnisharp-atom#54]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
DockView.initialize (/Users/alexandr/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/dock-view.coffee:62:9)
```

**Comment by dumle29** [comment]
Seconded. This is causing 15 warnings in atom 0.180.0

**Comment by VirtualOverride** [comment]
same thing happen for me. 
![warning](https://cloud.githubusercontent.com/assets/6830923/6361974/c68aa666-bcc2-11e4-8d66-2509ecb8862d.png)

**Comment by willl** [comment]
I'm wondering if PR #63 fixes this issue?

**Comment by VirtualOverride** [comment]
@willl thanks i will try that.

**Comment by VirtualOverride** [comment]
after changing from workspace to atom-workspace the Deprecated selectors warning disappear but the Deprecated calls still there.

![screen shot 2015-02-26 at 11 45 46 am](https://cloud.githubusercontent.com/assets/6830923/6386012/547edd12-bdad-11e4-87c3-4c172cbf5d4b.png)

**Comment by ctolkien** [comment]
Fixed.
