### ISSUE TITLE
Upgrading to OS X El Capitan breaks Atom/OmniSharp

### ISSUE THREAD

**Issue by gsscoder** [OmniSharp/omnisharp-atom#548]
I'm posting rather on Atom repository since the dialog that suggest me to post this issue contains the **OminSharp** _flame logo_.

The issue is exactly what I wrote in the subject of this post.

![schermata 2015-10-23 alle 13 53 42](https://cloud.githubusercontent.com/assets/1194228/10691965/f8c1fe44-798d-11e5-821b-dae806983472.png)

**Comment by willl** [comment]
Basically there's an issue with El Capitain and things in /usr/bin from memory. This StackOverflow post should sort you out: http://stackoverflow.com/questions/32542535/mono-installed-on-mac-but-not-recognized-in-terminal

**Comment by nosami** [comment]
Pretty sure this is coming from one of the ionide packages. OmniSharp-atom works fine on El Capitan.

I see this too with ionide installed, although I haven't dug any further. Disabling all ionide packages removes the error.

**Comment by gsscoder** [comment]
@nosami, I can confirm with an high grade of certainity because I've installed `ionide` few day before `El Capitan`; so maybe things are really related.
