### ISSUE TITLE
EPERM, unlink Microsoft.CodeAnalysis.CSharp.dll when updating

### ISSUE THREAD

**Issue by afontaine** [OmniSharp/omnisharp-atom#552]
On Windows, every update I perform fails with an EPERM error releated to unlinking some library or other.

```
Installing omnisharp-atom@0.25.10 to C:\Users\afontaine\.atom\packages failed
EPERM, unlink 'C:\Users\afontaine\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\roslyn\packages\dnx-clr-win-x86.1.0.0-beta4\bin\Microsoft.CodeAnalysis.CSharp.dll'
```

Do I need admin privileges to update omnisharp-atom on Windows?

**Comment by nosami** [comment]
It's a known issue with the Windows updater. It can't replace the executables while in use.

For now, close Atom, then `apm install omnisharp-atom` from the command line.

**Comment by afontaine** [comment]
Ah understandable. Thanks!
