### ISSUE TITLE
Uncaught Could not find a solution for location /Users/roberto/Development/csharp-demo/demo.cs

### ISSUE THREAD

**Issue by rcarrillopadron** [OmniSharp/omnisharp-atom#553]
1. I opened a new project on folder /a
2. I created a new C# file on folder /b/file.cs
3. It failed.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.10

### Stack Trace

Uncaught Could not find a solution for location /Users/roberto/Development/csharp-demo/demo.cs

```
At /Users/roberto/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:77

undefined
```

### Commands

```
     -0:51.4.0 application:new-file (div.panels-item)
  3x -0:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.10.0
omnisharp-atom, v0.25.10

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Very strange, I'm trying to replicate it now, and I can't figure out why you're getting this failure.  Anything else that you remember that might help draw out the exact scenario?

**Comment by rcarrillopadron** [comment]
The only thing I did was to install Omnisharp from the command line. Don't know if that helps.

**Comment by david-driscoll** [comment]
Same as the other related issues, without a .sln, project.json, or other files, omnisharp-roslyn doesn't run correctly, so we don't specificly bind to it.  I've converted the error to a info notification, as it really isn't an error, but just a notice.
