### ISSUE TITLE
intellisense work intermittent

### ISSUE THREAD

**Issue by aolba** [OmniSharp/omnisharp-atom#554]
I tought I found a solution in https://github.com/OmniSharp/omnisharp-atom/issues/456, but the true is sometimes I have intellisense active others don't. I can't find a pattern for the problem.
I use the workflow from Claytonious, it works... but when I reopen the proyect in Unity and link to Atom again. Intellisense is absent.

**Comment by david-driscoll** [comment]
This is solved with #563 thanks to @brad-jones for having some awesome repro steps I found out where I messed up.  Please update to the latest version using `apm` and you should be good to go.  Let me know if you run into any other problems!
