### ISSUE TITLE
Won't Recognize Unity3D Projects

### ISSUE THREAD

**Issue by jguarShark** [OmniSharp/omnisharp-atom#560]
I see that this was discussed in an earlier issue, but that one seemed to be resolved, so I thought it best to start a new issue.

I can't seem to get omnisharp-atom to recognize Unity3D projects on my desktop Mac, but it works fine on my MacBook using the same files. Go figure. 

I get the green flame icon, but zero projects.

Any thoughts? Thanks!

**Comment by tmunro** [comment]
If you look at the logs, do you see an exception? It seems to crash on the default Unity solution, so you'll need to remove this section:

    GlobalSection(SolutionProperties) = preSolution
        HideSolutionNode = FALSE
    EndGlobalSection

Be sure to remove the extra line at the end before EndGlobal.

**Comment by jguarShark** [comment]
Thanks. That fixed it right up.
