### ISSUE TITLE
IntelliSense / AutoComplete - Incompatibility with atom-typescript

### ISSUE THREAD

**Issue by brad-jones** [OmniSharp/omnisharp-atom#563]
Finally I think I have got to the bottom of this intermittent autocomplete failure.

I have a project (closed source unfortunately so can't provide details to use as a use case but happy to setup a mock project with the same structure) that has a C# server side backend and a TypeScript frontend.

### The following is repeatable every single time:

1. Open atom at project root
2. Open a C# file first
3. Open a TypeScript file second
4. Auto-complete for both languages works as expected.

OR

1. Open atom at project root
2. Open a TypeScript file first
3. Open a C# file second
4. Auto-complete for TypeScript works fine but in the C# file, no ```/autocomplete``` Omnisharp requests are ever made at all.

### VERSIONS:
atom @ v1.1.0
omnisharp-atom @ v0.25.10
atom-typescript @ v7.12.0

I would be interested to know if the users that created both: #554 & #540 
Also have atom-typescript installed.

**Comment by david-driscoll** [comment]
... :+1: on finding the repro, cause I would have never noticed that.

That said... wtf is going on... *sigh*

**Comment by david-driscoll** [comment]
Think I got it nailed, going to do some more testing tomorrow to make sure though.

**Comment by david-driscoll** [comment]
@brad-jones have you had a chance to test this lately?  I think I got it nailed with one of the latest versions.  If you still notice a problem just reopen. :+1:
