### ISSUE TITLE
Installing “omnisharp-atom@0.1.6” failed.

### ISSUE THREAD

**Issue by igorushi** [OmniSharp/omnisharp-atom#57]
I'm trying to install omnisharp-atom for a first time and get this error. I do have GIT installed and it's in my path !!!

npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) undefined
npm ERR! git clone https://github.com/Benvie/harmony-collections.git undefined
npm ERR! git clone https://github.com/Benvie/harmony-collections.git undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\XXXXX\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\XXXXX\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\XXXXX\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\.apmrc" "--userconfig" "c:\\Users\\XXXXX\\.atom\\.apmrc" "install" "C:\\Users\\XXXXX\\AppData\\Local\\Temp\\d-11514-4476-8wzzwm\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by dumle29** [comment]
See this:
https://atom.io/docs/latest/build-instructions/windows

If you have trouble installing SDK 7.1, uninstall all C++ 2010 x86 and x64 Redistributables. That helped me.

Take a look at [this](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/6e6c8a17-1666-42fa-9b5b-dfc21845d2f9/error-installing-windows-7-sdk-71-with-vs2008-vs2010-premium-on-win-7-32bit?forum=windowssdk) thread if you encounter install issues with SDK 7.1

**Comment by david-driscoll** [comment]
@igorushi Let us know if this is still  a problem with the latest version of atom and omnisharp-atom.

Thanks!

**Comment by igorushi** [comment]
now it installs with no problem, thanks.
