### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rog1039** [OmniSharp/omnisharp-atom#58]
Received this error when attempting to start the Omnisharp server....not sure what I did wrong here.

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.1.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /C:/Users/paulrogero/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni-sharp-server.coffee:117

TypeError: undefined is not a function
  at OmniSharpServerInstance.module.exports.OmniSharpServerInstance.getPortNumber (C:\Users\paulrogero\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni-sharp-server.coffee:106:25)
  at OmniSharpServerInstance.module.exports.OmniSharpServerInstance.start (C:\Users\paulrogero\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni-sharp-server.coffee:68:17)
  at OmniSharpServerInstance.module.exports.OmniSharpServerInstance.toggle (C:\Users\paulrogero\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni-sharp-server.coffee:114:50)
  at Object.module.exports.toggle (C:\Users\paulrogero\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.coffee:72:27)
  at atom-workspace.<anonymous> (C:\Users\paulrogero\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.coffee:14:61)
  at atom-workspace.handler (C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\paulrogero\AppData\Local\atom\app-0.177.0\resources\app\src\window-event-handler.js:170:20)

```

### Commands

```
     -0:40.6 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:03.7 omnisharp-atom:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.11
language-csharp, v0.3.0
omnisharp-atom, v0.1.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by cecilphillip** [comment]
Identical issue on OSX

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.1.6

**Comment by mholub** [comment]
Same issue for both latest OSX and Windows 8.1

**Comment by Mpdreamz** [comment]
Hi guys we are updating omnisharp atom to work with the latest `atom` and `autocomplete-plus` 

The 1.6 version still depends on `autocomplete-plus-async` (the readme has already been updated). 

Please bear with us for a couple of days while we sort it out!

**Comment by piranout** [comment]
Ditto here. This looks like a great package if I can get it working. 

**System** Windows 7, 
**Atom Version** 0.177.0,
**omnisharp-atom** 0.1.6,
**language-csharp** 0.5.0,
**autocomplete-plus-async** 0.22.0,
**atom-sharp** 0.1.0

**Comment by L4D15** [comment]
Same problem here in OS X 10.10. Is there some conflict between having autocomplete-plus and autocomplete-plus-async?

**Comment by ctolkien** [comment]
Just throwing my :+1:  into the ring here.

**Comment by tmunro** [comment]
I have this same problem - I assume you folks are updating for a 0.2 or 0.1.7 - so I pulled latest, changed the specific versioning requirements for `autocomplete-plus` and `language-csharp` to `>=`, and stomped over my local copy.

That got things mostly working, although obviously if something doesn't work I'll blame myself :)

**Comment by piranout** [comment]
**tmunro**, I'm brand new to Atom; could you give us some details on where to change the versioning requirements? If you also disclose which ‘local copies’ you're referring to, I shall forthwith commence stomping thereupon. :-)

**Comment by gblmarquez** [comment]
Hi,

Any workaround for this issue?

**Comment by tmunro** [comment]
Here's the workaround I employed, in detail:

1. Pull the latest omnisharp-atom code with APM and link it for dev: `apm dev omnisharp-atom`
2. Navigate to the new omnisharp directory, probably `~/github/omnisharp-atom`
2. Replace the `apmPackageDependencies` in `package.json` with those in this commit: https://github.com/tmunro/omnisharp-atom/commit/d67221e7013bc93484f5df00f505d76b169fecf3
3. Copy the whole directory.
4. Navigate to Atom's packages directory, probably `~/.atom/packages/`
5. Delete the omnisharp-atom folder there.
6. Paste your new folder.
7. Reload Atom.

That should work. If you want to test it out beforehand, you can open a dev window from inside of Atom with the command palette. That will load the dev version of the package and make sure it works before you copy it over the live version.

Hope that helps. I'm sure this will be unnecessary soon.

**Comment by SolidNerd** [comment]
:+1:  It works. Thank you very much :smiley:

**Comment by dumle29** [comment]
@tmunro This no longer works for me in 0.181.0 Using this I get no flame icon in the bottom left, and it doesn't respond to any keybindings

**Comment by filimon-danopoulos** [comment]
@Mpdreamz  Any news regarding this issue? A couple of days have passed.

**Comment by tmunro** [comment]
@dumle29 I just fixed it for 0.181.0, looks like the way of getting the project's path changed. You'll need the steps I did above plus the changes in this commit: https://github.com/tmunro/omnisharp-atom/commit/b7f21dc6bfef439443b92339f63593a550970efe

**Comment by dumle29** [comment]
@tmunro Thank you very much :)

**Comment by Mpdreamz** [comment]
Just updated the package with the path path fix 

https://atom.io/packages/omnisharp-atom

**Comment by tmunro** [comment]
@Mpdreamz: Is the `^0.3.0` requirement for Language Csharp intentional? Is the package not supposed to work with 0.5.0? I'm assuming what you want `>= 0.3.0 and < 1.0.0` which is `^x.3.0` or something like that.

**Comment by stephen-james** [comment]
@tmunro, nope that's not intentional I used a caret range in error - it should be >= as you mention.  Will change this asap

**Comment by Mpdreamz** [comment]
thanks for the ping @tmunro, relaxed the dependency and pushed `0.2.1` :+1:

**Comment by nosami** [comment]
Just got this error when updating from 0.23.2 to 0.24.0

**Comment by L4D15** [comment]
I'm also experiencing it. In previous versions I could get rid of it launching Atom from the terminal so it used the Mono installed from Brew instead of the one from Unity3D, but now that doesn't work either.

**Comment by L4D15** [comment]
BTW I updated from 0.23.1 to 0.24.0.

**Comment by nosami** [comment]
@L4D15 The launcher script is at ~/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/Omnisharp

It uses brew installed mono by default now.

```bash
#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export SET DNX_APPBASE="$DIR/packages/OmniSharp/1.0.0/root"

export PATH=/usr/local/bin:$PATH # this is required for the users of the Homebrew Mono package

exec "$DIR/packages/dnx-mono.1.0.0-beta4/bin/dnx" "$DNX_APPBASE" run "$@"
```
