### ISSUE TITLE
Enhanced Highlighting Causes Hang On C# Files

### ISSUE THREAD

**Issue by jguarShark** [OmniSharp/omnisharp-atom#580]
Omnisharp has begun causing Atom to hang when switching to specific C# files.

After much turning on/off of packages and settings, I've found that the problem disappears if I turn off Enhanced Highlighting.

**Comment by david-driscoll** [comment]
If the project is open source and you have the source file that hang
happens on, please let me know, that help's a ton in identifying where the
hang is at.

**Comment by jguarShark** [comment]
It's not open source, but I'd be happy to send it to you if need be.

**Comment by david-driscoll** [comment]
It's up to you on that part. :smile:

My email is david.driscoll at gmail.com

**Comment by jguarShark** [comment]
Files sent.

**Comment by david-driscoll** [comment]
So I've pushed monkey patch, that should stop atom from locking up on C# editors when we don't quiet modify the tokenization properly.

If you notice any artifacts, like a tokenized line that goes on and on, when it shouldn't, follow that up with an issue, as we might need to address that.
