### ISSUE TITLE
Uncaught Could not find a solution when opening a standalone .cs file

### ISSUE THREAD

**Issue by breiter** [OmniSharp/omnisharp-atom#581]
Omnisharp throws an exception when I use Atom to open a .cs file which isn't part of a solution. For example a scratch file that can be built with a one-line csc or mcs at the command-line.
1. Have a .cs file in a directory without a solution.
2. Open the file with `atom file.cs`
3. Exception is thrown.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.1

### Stack Trace

Uncaught Could not find a solution for location /Users/breiter/src/breiter/attic/NewPassword/NewPassword.cs

```
At /Users/breiter/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:77

undefined
```

### Commands

```
     -1:08.2.0 settings-view:open (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:56.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "wrap-guide",
      "sync-settings"
    ],
    "themes": [
      "one-dark-ui",
      "zenburn"
    ]
  },
  "omnisharp-atom": {
    "codeLens": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-yeoman, v0.3.15
color-picker, v2.0.14
go-plus, v3.5.2
json-schema, v0.1.15
language-apache, v1.3.0
language-cshtml, v0.1.1
language-diff, v0.4.0
language-powershell, v2.1.0
linter, v1.11.3
omnisharp-atom, v0.26.1
pigments, v0.19.1
zenburn, v3.0.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
I've published a fix, that will make this an info notification instead of a popup, right now OmniSharp Roslyn doesn't support editing lone .cs files (omnisharp-server on the other hand does).  Once this gets fixed on the server side we'll come back readdress this at that time.
