### ISSUE TITLE
Needs package language-csharp even though it's installed

### ISSUE THREAD

**Issue by jkells** [OmniSharp/omnisharp-atom#59]
I followed the instructions in the Readme. When I press ctrl+alt+o a dialog appears with the following message

Omnisharp Atom needs the package `language-csharp` (version ^0.3.0) to be installed. You have an older version 0.5.0.

This is a fresh install of Atom on Windows 8.1

**Comment by VirtualOverride** [comment]
same issue with me. but i used mac OS X 
![error](https://cloud.githubusercontent.com/assets/6830923/6324052/d7e84396-bb6e-11e4-9d1d-90dbd1038b30.png)

**Comment by stephen-james** [comment]
Thanks this is a bug, the semver is using a caret range in error and should be using >= (as pointed out by @tmunro in another issue) will be sorting it out soon

**Comment by VirtualOverride** [comment]
thanks @stephen-james

**Comment by Mpdreamz** [comment]
Thanks for the feedback guys just relaxed dependency and pushed `0.2.1`

**Comment by stephen-james** [comment]
:+1:

**Comment by VirtualOverride** [comment]
@Mpdreamz cool thanks
