### ISSUE TITLE
[Wish] IronPython

### ISSUE THREAD

**Issue by mostaphaRoudsari** [OmniSharp/omnisharp-atom#593]
Any chance that omnishatp-atom can be used for IronPython development? Current auto-complete packages for Python supports auto-complete for IronPython dlls.

**Comment by david-driscoll** [comment]
It might be possible to implement an out of process plugin for OmniSharp that would run tooling for IronPython, but that isn't on the road map today anyway.

You can make an issue over at https://github.com/OmniSharp/omnisharp-roslyn/issues to better track it, and if you can include any details like if IronPython has any opensource tooling bits,just to make things easier. :smile:

**Comment by mostaphaRoudsari** [comment]
Hi @david-driscoll, Thank you for the quick reply. Added [here](https://github.com/OmniSharp/omnisharp-roslyn/issues/372)
