### ISSUE TITLE
Option to disable advanced-open-file?

### ISSUE THREAD

**Issue by dill0wn** [OmniSharp/omnisharp-atom#618]
There's an option to disable `advanced-new-file`, but it seems there isn't one for `advanced-open-file`.  I'd really like to bind something else to ctrl-n, but `advanced-open-file:toggle` with the selector `atom-text-editor:not([mini]).omnisharp-editor` always takes precedence.  I'd like to be able to change that without having to disable the default omnisharp-atom binds and rebind everything manually.  

However, maybe that's what I need to do. Or maybe there is a different solution to my conundrum?

**Comment by david-driscoll** [comment]
It's entirely possible that it doesn't work at the moment, I can take a look.
