### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by VirtualOverride** [OmniSharp/omnisharp-atom#62]
Do i need to have project file? i encounter error when executing build
![build-error](https://cloud.githubusercontent.com/assets/6830923/6362109/5745d828-bcc4-11e4-8f6c-04af764faf0b.png)

**Comment by nosami** [comment]
omnisharp-atom doesn't support vnext projects yet. The backend needs switching over at some point to use omnisharp-roslyn.

**Comment by VirtualOverride** [comment]
ah ic thanks. i will use command line to build the vnext project.

**Comment by VirtualOverride** [comment]
@ctolkien how can i fix that? should i update my omnisharp-atom? thanks

**Comment by ctolkien** [comment]
@VirtualOverride  - hang tight whilst we get this PR merged into master, then we'll get a new version of the package out. If you're feeling adventurous, you can drop my fork in over the top (https://github.com/ctolkien/omnisharp-atom) (then run npm install from the package directory). 

The concept of "building" doesn't translate over exactly to vnext, so this section might see some further changes.

**Comment by VirtualOverride** [comment]
@ctolkien thanks apologies for being excited. i will give it a try to fork it.

**Comment by willl** [comment]
@VirtualOverride Roslyn based OmniSharp Atom has been released now (0.3.0)!

**Comment by david-driscoll** [comment]
@VirtualOverride Roslyn is now out the door, closing the ticket.  Please feel free to give it a shot and let us know!
