### ISSUE TITLE
Version 0.26.9 stuck on 'Install'

### ISSUE THREAD

**Issue by tobygrichards** [OmniSharp/omnisharp-atom#625]
As per the title, is there a work around or a way of installing a specific version?

**Comment by willl** [comment]
Perhaps try installing it from the [command line/terminal](https://atom.io/docs/latest/using-atom-atom-packages)?

Eg: `apm install omnisharp-atom`

Or for a specific version
`apm install omnisharp-atom@0.26.9`

**Comment by tobygrichards** [comment]
Thanks for your suggestions, I ended up installing it by downloading the
source, copying it to users/username/.atom/packages then running npm
install from that directory.
