### ISSUE TITLE
Icons overlap on status bar

### ISSUE THREAD

**Issue by Stephn-R** [OmniSharp/omnisharp-atom#627]
OS: El Capitan on Macbook Air 13"

![image](https://cloud.githubusercontent.com/assets/5117415/12587452/72ccdc7a-c422-11e5-92ef-af393c58f308.png)

**Comment by ccbentlee** [comment]
Maybe you didn't open a C# project.I had this problem before because I didn't open my project.BTW, I can't open any project :( .The pulse icon always shows "Downloading" and the green fire icon never lighten up since I last update omnisharp.
