### ISSUE TITLE
exec: mono: not found

### ISSUE THREAD

**Issue by spboyer** [OmniSharp/omnisharp-atom#629]
v 0.2.69, default settings.

Getting the following issue in a new project.
```
Starting OmniSharp server (pid:undefined)
OmniSharp Location: /Users/<username>/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/run
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: /Users/<path to project folder>
/Users/<username>/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/runtimes/dnx-mono.1.0.0-rc2-16388/bin/dnx: line 14: exec: mono: not found
```

@david-driscoll

**Comment by spboyer** [comment]
Have mono installed via Homebrew, also installed via mono-project as well. Did not fix. Project is coreclr, no mono in project.json. Meaning no dotnet 4.5.1

**Comment by david-driscoll** [comment]
odd, might be related to the homebrew mono, I'll see what I can do there.

**Comment by david-driscoll** [comment]
@spboyer client is building, I hope it will fix it.  I might have to fiddle with the build a bit before I can get it merged.

I have to force travis to give me a mono-less mac and then install mono with brew, lol.
