### ISSUE TITLE
Unable to re-order editor tabs by dragging when omnisharp-atom is enabled

### ISSUE THREAD

**Issue by n3dst4** [OmniSharp/omnisharp-atom#631]
Normally, it's possible to change the order of tabs in an atom editor window by clicking and dragging. When omnisharp-atom is installed and enabled, tabs no longer respond to the drag action at all (although the initial mousedown still switches focus).

Atom version: 1.4.1
omnisharp-atom version: 0.26.9
OS: Windows 7 64bit

This is observed using a clean atom profile with nothing installed but omnisharp-atom and it's dependencies.

There is also some console output from this line in [`omnisharp-atom/lib/views/dock-window.js`](https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/views/dock-window.ts#L91) whenever dragging is being attempted.

**Comment by Daniel15** [comment]
I was seeiong this too, but upgrading to the latest OmniSharp package (0.26.13) seems to have fixed it.

**Comment by n3dst4** [comment]
Agreed, it seems to be fixed in 0.26.13.
