### ISSUE TITLE
OmniSharp requires outdated autocomplete-plus package

### ISSUE THREAD

**Issue by VorT3x** [OmniSharp/omnisharp-atom#67]
Wanted to start using omnisharp in Atom.
Installed everything:
apm install language-csharp
apm install autocomplete-plus
apm install omnisharp-atom

But when I press toggle in omnisharp menu I get this:
![screen shot 2015-03-02 at 19 37 44](https://cloud.githubusercontent.com/assets/883328/6446415/bd70006c-c113-11e4-8f13-6136c8051764.png)

But current autocomplete-plus version is 2.3.0

**Comment by VorT3x** [comment]
Heh, it looks like I've installed omnisharp-atom BEFORE autocomplete-plus. Re-installed omnisharp and don't get this error.

**Comment by stephen-james** [comment]
Is there any chance you installed omnisharp a week or so ago before trying it more recently?  The last release from @mpdreamz addressed the version detection bug that you had there, so I don't think it was related to the order in which things were installed - that shouldn't matter.  Glad it's working for you now though!
