### ISSUE TITLE
If you have spaces in username, OmniSharp crashes.

### ISSUE THREAD

**Issue by ozdemiremre** [OmniSharp/omnisharp-atom#683]
![capture12](https://cloud.githubusercontent.com/assets/8995420/13711216/148fb494-e7c6-11e5-86ac-76725e0e1ffe.PNG)

As you can see from the screen grab, OmniSharp can't handle if you have spaces in your username. 

I'm guessing this is related to this previous issue: https://github.com/OmniSharp/omnisharp-atom/issues/466

Any ideas ?

**Comment by david-driscoll** [comment]
I'm putting in the following change, it should get dropped with the next release.  Hopefully it'll work, I don't have a good test case just yet, but once I do I can make some more tests myself.

https://github.com/OmniSharp/omnisharp-node-client/pull/156
