### ISSUE TITLE
OmniSharp Server does not start, no output

### ISSUE THREAD

**Issue by Incand** [OmniSharp/omnisharp-atom#712]
Hello,

I wanted to install the OmniSharp package for Unity3D developement and after trying for many hours still didn't get it to work.
The flame symbol is there but never green, toggling OmniSharp does nothing and the output is empty:

![001](https://cloud.githubusercontent.com/assets/11589690/14604180/6d182eec-0572-11e6-9c22-7774c8ef7740.png)

Edit: I should have mentioned that my System is running Linux-Mint. I think its save to say, that this issue is only affecting Linux systems.

**Comment by CyanBlob** [comment]
@Incand Did you ever figure out what your issue was with this?

**Comment by rileytippetts** [comment]
@CyanBlob Just updated my own Unity version and Omnisharp-atom package and I'm having the same issue. Opening the project in Atom and selecting a file fails to start the server. Any idea what might be happening? I'm also on Mac.

**Comment by Incand** [comment]
@CyanBlob I got it to work but I can't remember exactly how. I played around a lot with the prerequisites as seen [here](https://github.com/OmniSharp/omnisharp-atom/wiki).
Also I tried using the newest (not release) version of omnisharp by compiling the repo with node.js.

**Comment by rileytippetts** [comment]
@Incand Can I ask what Unity version you are using?

**Comment by Incand** [comment]
@rileytippetts 5.3.6f1 Personal

**Comment by rileytippetts** [comment]
@Incand Ok, thanks. Have you been having problems with Unity's external editor setting in preferences by any chance? Recently I noticed that setting Atom to be the default editor and selecting 'Assets/Open C# Project' will launch both Atom and MonoDevelop, and only MonoDevelop will work properly.

Also, I managed to get Omnisharp running with Atom, however I get the following errors:

```
The project system 'MSBuildProjectSystem' threw exception during initialization.
The type initializer for 'Crypto' threw an exception.
   at Interop.Crypto.EvpMd5()
   at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
   at System.Security.Cryptography.MD5.Implementation..ctor()
   at OmniSharp.MSBuild.MSBuildProjectSystem.UnityTypeGuid(String projectName) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 187
   at OmniSharp.MSBuild.MSBuildProjectSystem.Initalize(IConfiguration configuration) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 68
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.Host/Startup.cs:line 183
```

With no intellisense or linter + I'm seeing "0 Projects" while the server is running :/

**Comment by Incand** [comment]
Besides Unity not opening the right file in atom if I double click it from the editor (which I guess is just a launch parameter issue) I have no such problems. Atom gets launched normally when I double click a .cs file or select 'Assets/Open C# Project'.

**Comment by hex3r** [comment]
Did you guys figure out how to tie Unity and Atom? I'm having the same exception @rileytippetts posted and can't get Atom to work with Unity (5.3.x)

**Comment by redgenco** [comment]
Anyone figure this out? Can't seem to find any solution online.

**Comment by lagidigu** [comment]
Did anyone find out what the problem was?

**Comment by Prograb** [comment]
Did y'all figured it out?
