### ISSUE TITLE
"Open the root of a solution?"

### ISSUE THREAD

**Issue by indyHarcourt** [OmniSharp/omnisharp-atom#77]
The readme says to "Open the root of your solution within Atom"
What, exactly, does that mean?  
How do I "open the root" of a solution?
What If I don't have a solution but just some random "sample.cs" file that I want to open and edit?

**Comment by Mpdreamz** [comment]
Hi @indyHarcourt 

It means use open folder to open the root folder of your application, typically the folder that has your sln file or project.json. 

You can open a sample.cs file but you cannot start the omnisharp-server on it (using ctrl+alt+o).
