### ISSUE TITLE
Failed to process project file

### ISSUE THREAD

**Issue by JD342** [OmniSharp/omnisharp-atom#773]
Maybe I'm being incredibly dense but I'm failing to make this package work, it fails to process my Unity3D and MonoDevelop projects. The `.sln` and `.csproject` files are correctly recognized but a failure to process the `.csproject` file is logged in the Omnisharp output.

![screenshot from 2016-06-18 12-46-51](https://cloud.githubusercontent.com/assets/11964463/16170433/c695089a-3552-11e6-9b0a-7504a36aa418.png)

[Here](/JD342/misc-data/tree/C%23-Hello-World-Experiment) is the source of the MonoDevelop project in the screenshot.

My distro (fresh installed) is Ubuntu GNOME 16.04 amd64 and I have installed the lastest version of Mono by following the instructions in their [website](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives) (the packages `mono-devel`, `mono-complete`, `monodevelop` and `mono-xsp4`).

```
$ mono --version
Mono JIT compiler version 4.4.0 (tarball Tue Jun 14 13:41:51 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen
$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
$ apm list --installed --bare
advanced-open-file@0.16.3
atom-yeoman@0.3.15
json-schema@0.1.15
linter@1.11.11
omnisharp-atom@0.29.4
```

**Comment by adamiak** [comment]
The exact same thing happens to me on OS X El Capitan.

**Comment by adamiak** [comment]
This problem no longer exists with omnisharp-atom 0.30.4. I guess this issue can be closed now.
