### ISSUE TITLE
OmniSharp.exe fails to launch due to System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by StevenTsvetkov** [OmniSharp/omnisharp-atom#779]
Hello,

I've been trying to get OmniSharp to work for several hours now, but all of my attempts were in vain. When I open a C# file, I get the following error in the Omnisharp Output:

```
Starting OmniSharp server (pid:32635)
OmniSharp Location: mono /home/steven/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/omnisharp-mono/OmniSharp.exe
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: /home/steven/test

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Program.Main (System.String[] args) <0x4076ad50 + 0x0012f> in <filename unknown>:0 

[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Program.Main (System.String[] args) <0x4076ad50 + 0x0012f> in <filename unknown>:0 
```

I do indeed have the requirements covered. I am running Ubuntu 16 with latest updates and I have the latest stable versions of the CLR and SDK (RC2 and Preview 1 respectively) and Mono version 4.2.1. 

From what I can tell, it's looking for System.Runtime, but it's just not there. I tried to manually restore the plugin's packages and some other stuff. What I am doing is that I create a new project with `dotnet new`, after which I run `dotnet restore` and `dotnet build`. When I try to open the C# file, this error occurs. Same happens when I try to start it from the terminal.

I'm sorry if this error is caused by some external factors, that are not related to OmniSharp, due to my ignorance . Thanks!

**Comment by Stev3nT** [comment]
My full Atom configuration can be found here: https://gist.github.com/Stev3nT/5450386acf3243a1f496c22f3125fd7f

**Comment by abourget** [comment]
I'm having the same issue here, and does the same with VSCode's C# plugin.. any insights ?

I'm on Ubuntu 16.04 and installed dotnet with these instructions https://www.microsoft.com/net/core#ubuntu

**Comment by niel** [comment]
Also having this problem on Linux Mint 18, follow links from VS Code which led to same instructions as @abourget linked above.

**Comment by steventsvetkov** [comment]
No longer relevant :)
