### ISSUE TITLE
How to configure OmniSharp for ASP.NET?

### ISSUE THREAD

**Issue by russjr08** [OmniSharp/omnisharp-atom#78]
It seems that by default OmniSharp doesn't recognize any of the ASP.NET packages, and as such, it believes there are errors everywhere.

Is there a proper way to reconfigure it so it recognizes it?

![image](https://cloud.githubusercontent.com/assets/773179/6817921/848ca520-d275-11e4-9f54-96570d054df3.png)

**Comment by ctolkien** [comment]
There's a new release coming Soon(tm) which supports ASP.NET5.

**Comment by russjr08** [comment]
Ah whoops, I should've totally checked which versions OmniSharp supported.

**Comment by ctolkien** [comment]
FYI @russjr08  - if you git pull this repo down into atom/packages, then  enter the directory and run npm install, it should work. We just haven't got the new bits into APM (atom's packager) yet.

**Comment by russjr08** [comment]
Oh wow, awesome! Thanks for the heads up :)
