### ISSUE TITLE
Unable to install omnisharp-atom@0.3.0

### ISSUE THREAD

**Issue by VintageXP** [OmniSharp/omnisharp-atom#784]
`apm install omnisharp-atom@0.30.0` gives the following error:

> spawn-sync@1.0.15 postinstall C:\Users\VINTAG~1\AppData\Local\Temp\apm-install-dir-116527->6920-18kw987\node_modules\omnisharp-atom\node_modules\generator->aspnet\node_modules\yeoman-generator\node_modules\yeoman->environment\node_modules\inquirer\node_modules\external-editor\node_modules\spawn-sync
> node postinstall
>
>
>npm WARN engine omnisharp-client@5.0.11: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
>npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest >version of pug instead of jade
>npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it >in the tree.
>npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a >RegExp DoS issue
>npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a >RegExp DoS issue
>npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a >RegExp DoS issue
>npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to >lodash@^4.0.0.
>npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
>npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
>npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
>npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
>npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine decompress-unzip@4.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine decompress-targz@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine decompress@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine strip-bom@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine decompress-tar@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine decompress-tar@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine decompress-tarbz2@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\VintageXP\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\VintageXP\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\VintageXP\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\VintageXP\\.atom\\.apmrc" "install" "C:\\Users\\VINTAG~1\\AppData\\Local\\Temp\\d-116527-6920-1fng2l6\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

>npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
>npm ERR! spawn ENOENT
>npm ERR! 
>npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
>npm ERR! This is most likely a problem with the spawn-sync package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node postinstall
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls spawn-sync
>npm ERR! There is likely additional logging output above.

**Comment by willl** [comment]
Could you try updating your version of npm? Yours seems to be v2.13.3 based on your log.

The current stable version is v3.10.2. In your command line/terminal run `npm install npm -g` ([ref](https://docs.npmjs.com/getting-started/installing-node#updating-npm)) to upgrade npm.

The issue seems to be with installing [spawn-sync](https://github.com/ForbesLindesay/spawn-sync). And their recommendation is to try upgrading npm.

Your issue seems similar to this one: https://github.com/ForbesLindesay/spawn-sync/issues/39

**Comment by VanCoding** [comment]
@willl I'm on Windows, and apm uses it's own version of npm which is still at version 2.x. So, upgrading the globally installed NPM does not help. Instead, we need a way to upgrade the NPM version of APM, or make it use the globally installed version.

But I have no idea how to do either.

**Comment by VintageXP** [comment]
Yeah, I did try to update npm. I've also tried other possible solutions from other posts that have a similar problem. I've tried installing it on linux (Fedora 23) and worked like a charm.

**Comment by david-driscoll** [comment]
It seems it's related to `generator-aspnet`... I'm currently testing a fix.  For the moment try 0.30.2, as I've removed it as a dependency.

**Comment by VintageXP** [comment]
Thanks, I'll try as soon as possible.

**Comment by VanCoding** [comment]
@VintageXP I was now able to install omnisharp-atom 0.30.3 on Windows 7.

But it does nothing. I don't even get the flame icon in the bottom left corner.
The readme says dnvm is needed, which I don't have installed, because I'm already using the latest dotnet CLI. Is this supported already?

**Comment by david-driscoll** [comment]
Probably just another issue, I'm out of town so my computer access is a little spotty at times.  I'll look at it shortly.

**Comment by david-driscoll** [comment]
I think I have it resolved with .30.4

**Comment by VanCoding** [comment]
@david-driscoll Damn, that was quick! It works now, thank you! :)

**Comment by VintageXP** [comment]
Yep, working fine now. Thanks for the help David.
