### ISSUE TITLE
Installing omnisharp-atom 0.30.0 hangs

### ISSUE THREAD

**Issue by PooSham** [OmniSharp/omnisharp-atom#787]
I waited about 10 minutes, but nothing happens. I still see 

> Installing omnisharp-atom@0.30.0 to C:{Home path}.atom\packages  

And no changes in the package folder. 

**Technical information:** 
I'm using Windows 10. 
Running "apm -v" gives the following output:

> apm  1.9.2
> npm  2.13.3
> node 0.10.40
> python
> git 2.9.0.windows.1
> visual studio

**Comment by david-driscoll** [comment]
I really wish apm let us push up archives... I'll have to take a look see if I can identify the problem.

**Comment by david-driscoll** [comment]
there may be a npm-debug.log or similar somewhere.

**Comment by PooSham** [comment]
There is one under _.atom\packages\atom-yeoman\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\spawn-sync_, but it's empty.
