### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by MichaelGarza** [OmniSharp/omnisharp-atom#79]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'value' of undefined

```
At /Users/mgarza/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/build-output-pane-view.coffee:34

TypeError: Cannot read property 'value' of undefined
  at ViewModel.vm.Vue.methods.navigate (/Users/mgarza/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/build-output-pane-view.coffee:34:63)
  at HTMLPreElement.handler (/Users/mgarza/.atom/packages/omnisharp-atom/node_modules/vue/src/directives/on.js:34:31)

```

### Commands

```
  2x -2:05.5 core:move-right (atom-text-editor.editor.is-focused)
 10x -2:04.9 core:backspace (atom-text-editor.editor.is-focused)
 34x -1:59.7 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:50.8 core:move-up (atom-text-editor.editor.is-focused)
 23x -1:50.2 core:move-right (atom-text-editor.editor.is-focused)
 26x -1:46.6 core:backspace (atom-text-editor.editor.is-focused)
     -1:39.4 autocomplete-plus:select-next (atom-text-editor.editor.is-focused)
     -1:38.6 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:38.4 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:37.9 core:move-right (atom-text-editor.editor.is-focused)
     -1:36.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:35.9 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -1:35.5 core:backspace (atom-text-editor.editor.is-focused)
 10x -1:33.1 core:move-down (atom-text-editor.editor.is-focused)
     -1:30.6 core:save (atom-text-editor.editor.is-focused)
     -1:22.7 omnisharp-atom:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.6.0
language-csharp, v0.5.0
minimap, v4.6.0
omnisharp-atom, v0.2.1
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by k0st1x** [comment]
also reproduced on windows platform

**Comment by david-driscoll** [comment]
@MichaelGarza @k0st1x any specific reproducible steps?  Can you retest with the latest atom and latest omnisharp-atom ?

**Comment by k0st1x** [comment]
@david-driscoll well done. thx

**Comment by ctolkien** [comment]
@k0st1x  - can we take the above comment to mean this is resolved?

**Comment by david-driscoll** [comment]
I am going too! :+1:

**Comment by PranavOFS** [comment]
I am getting the following error "Uncaught TypeError: Cannot read property 'focusScope' of undefined" in the atom editor. Can you tell how to resolve this?

**Comment by willl** [comment]
@PranavOFS Could you please provide some reproducible steps to demonstrate how the error occurred?

**Comment by PranavOFS** [comment]
I just installed atom editor last week. It was fine last week. Today i just opened it. The error occured. so am not sure about the reproducible steps. I ll share the type error below.

TypeError: Cannot read property 'focusScope' of undefined
  at ScopePathView.module.exports.ScopePathView.onEnterButton (C:\Users\pranav.OFS1\.atom\packages\scope-inspector\lib\scope-path-view.coffee:44:29)
  at HTMLDivElement.handler (D:\tools\atom\app-0.201.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (D:\tools\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (D:\tools\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
