### ISSUE TITLE
'C:' could not be spawned

### ISSUE THREAD

**Issue by aivascu** [OmniSharp/omnisharp-atom#81]
When I try to build my solution I'm getting the following error message: 
*'C:' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.*
![ekistqd](https://cloud.githubusercontent.com/assets/7030530/6884910/c40f917e-d60f-11e4-8ab0-cdfa7228d120.png)

**Comment by RichiCoder1** [comment]
:+1: 
Looking at `build.coffee`, it looks like the `pattern` is bad, at least on windows.
The "args" are:
```
0: "Windows"
1: "Microsoft.NET"
2: "Framework64"
3: "v4.0.30319"
4: "Msbuild.exe"
5: "/m"
6: "/nologo"
7: "/v:q"
8: "/property:GenerateFullPaths=true"
9: "C:"
10: "Source"
11: "ecurit"
```
with the command being:
`"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Msbuild.exe /m /nologo /v:q /property:GenerateFullPaths=true "C:\Source\security""`
