### ISSUE TITLE
Does not work with 3rd party, NuGet installed dependency

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/omnisharp-atom#82]
```
"version": "0.2.1",
```
OS X/Atom 0.188

I've been trying to follow M101DotNet MongoDB course using only OmniSharp - but I've encountered a serious problem. I'm not able to get it working correctly within Atom (not yet tested in other IDEs).
My dependency from project via `kpm list`:
```
kpm list
List dependencies for M101DotNet (/Users/piotrblazejewicz/git/m101DotNet-vNext/M101DotNet/project.json)
[Target framework Asp.Net]
M101DotNet 1.0.0
    -> 
framework/Microsoft.CSharp 4.0.0.0
    -> M101DotNet 1.0.0
MongoDB.Bson 2.0.0-rc0
    -> MongoDB.Driver 2.0.0-rc0, MongoDB.Driver.Core 2.0.0-rc0
MongoDB.Driver 2.0.0-rc0
    -> M101DotNet 1.0.0
MongoDB.Driver.Core 2.0.0-rc0
    -> MongoDB.Driver 2.0.0-rc0
framework/mscorlib 4.0.0.0
    -> M101DotNet 1.0.0
framework/System 4.0.0.0
    -> M101DotNet 1.0.0
System.Console 4.0.0-beta-22613
    -> M101DotNet 1.0.0
framework/System.Core 4.0.0.0
    -> M101DotNet 1.0.0
System.IO 4.0.10-beta-22231
    -> System.Console 4.0.0-beta-22613
System.Runtime 4.0.20-beta-22231
    -> System.Console 4.0.0-beta-22613, System.IO 4.0.10-beta-22231, System.Text.Encoding 4.0.10-beta-22231, System.Threading.Tasks 4.0.10-beta-22231
System.Text.Encoding 4.0.10-beta-22231
    -> System.IO 4.0.10-beta-22231
System.Threading.Tasks 4.0.10-beta-22231
    -> System.IO 4.0.10-beta-22231
```
The OmniSharp does not recognize 3rd party:
![20150329225104](https://cloud.githubusercontent.com/assets/14539/6887644/1f50340c-d666-11e4-8e73-a466979f676e.jpg)

That's not just MongoDB package, I've used Newtonsoft.Json package and had that problem as well.

I've used generator-aspnet `Console` template to scaffold this project - but it just works - except of OmniSharp plugin within Atom IDE.
I"m interested in solving this - I had to use my PC/work machine at home to follow M101DotNet course.

Thanks!

**Comment by ctolkien** [comment]
The current version of omnisharp-atom via APM isn't based off the Roslyn version of Omnisharp - as such it doesn't support `project.json` project systems.

>I'm interested in solving this - I had to use my PC/work machine at home to follow M101DotNet course.

To run the current master (which is based off of Roslyn - and does support project.json), you can git clone this repo into your atom/packages directory, then jump in the directory and run `npm install`. That should get it up and running.

**Comment by peterblazejewicz** [comment]
@ctolkien Chad, thanks for the response and sorry for my late reply (all day at work, etc).
It did work, really fantastic!
