### ISSUE TITLE
Move to typescript

### ISSUE THREAD

**Issue by Mpdreamz** [OmniSharp/omnisharp-atom#85]
Atom will/already does support `.ts` files OOTB now!

https://github.com/atom/atom/pull/5898

we could try https://www.npmjs.com/package/coffee-script-to-typescript to do the conversion automatically. 

I personally like coffeescript/typescript equally but the overwhelming consensus in #omnisharp on jabbr is in favor of TS so lets move this sucker over :smile:

**Comment by willl** [comment]
So what's the action plan? Create a new branch for the TypeScript version?

Based on observation of the earlier #omnisharp conversations, the move to TS would potentially mean more contributors to this package.

**Comment by basarat** [comment]
@willl asked me to voice my opinion so here it is: 

Considering the number of files (under 50) I would be tempted to just rewrite files by hand on by one. I've been doing that when porting over other peoples coffeescript stuff to typescript.  Consider: 

https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/features/rename.coffee

I would just rename to `rename.ts` and start hacking: 

```
var _ = require('underscore')
var RenameView = require ('../views/rename-view')
var Omni = require ('../../omni-sharp-server/omni')

class Rename {
   // You get the idea. 
}

export = RenameView
```

For views I would leave the ones that are okay in Coffee e.g. : https://github.com/OmniSharp/omnisharp-atom/blob/master/lib/omnisharp-atom/views/omni-output-pane-view.coffee 

You can even leave the `html` portion in a coffeescript file that your `ts` view requires : e.g. https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/views/renameView.ts#L3 
and coffee https://github.com/TypeStrong/atom-typescript/blob/master/views/renameView.html.coffee 
Note: I was still messing around at that time. And I would (and did) place the html next to the ts file but collabs wanted it the way it is, i.e. all coffee in one place : https://github.com/TypeStrong/atom-typescript/tree/master/views

The thing that will absolutely drive you up the wall is heavy use of `?` in coffeescript. The TS alternative is extremely verbose to write out ( vote on this : https://github.com/Microsoft/TypeScript/issues/16 )

:rose:

**Comment by ctolkien** [comment]
I'm completely green with typescript as well, but I'd support this migration! :+1:

**Comment by david-driscoll** [comment]
I'd be willing to help as well.

**Comment by nosami** [comment]
@will, @david-driscoll and @ctolkien have offered to migrate this over. Why don't we make them contributors so they can collaborate more easily?

**Comment by will** [comment]
Please do not make me a contributor

**Comment by nosami** [comment]
@will - oops, fixed :)

**Comment by will** [comment]
:)

**Comment by nosami** [comment]
I suggested on JabbR that we make a list similar to this one (https://github.com/OmniSharp/omnisharp-roslyn/issues/29) with each file listed. Then when someone wants to work on that file, they can just put there name next to it.

**Comment by basarat** [comment]
Also don't use initialize : https://github.com/TypeStrong/atom-typescript/blob/master/docs/spacepen.md

**Comment by willl** [comment]
It's happening #98. :)

**Comment by willl** [comment]
Current code in master is now in TypeScript now that 0.3.0 has been released. Contributions always welcome :)

**Comment by david-driscoll** [comment]
Since we pushed 0.4.0 as typescript, I think we can close this! :tada:
