### ISSUE TITLE
Error trying to build C# code

### ISSUE THREAD

**Issue by usersxm** [OmniSharp/omnisharp-atom#87]
At first I have some troubles with mono when trying to toggle omnisharp, and then I reinstalled it and worked. But now I'm have issues when trying to build a simple "hello world" code
![captura de pantalla 2015-04-02 21 20 49](https://cloud.githubusercontent.com/assets/9682572/6976324/775b1458-d97e-11e4-857a-20935978d002.png)

and also I don't know if it has something to do with this but atom shows that I have some deprecations:
![captura de pantalla 2015-04-02 21 20 18](https://cloud.githubusercontent.com/assets/9682572/6976329/8dcc1ff2-d97e-11e4-9f6f-afeac9e0655e.png)

**Comment by peterblazejewicz** [comment]
@usersxm 
Which version of package you're using? The latest public via Atom repository is 2.1.0:
https://github.com/OmniSharp/omnisharp-atom/releases

**Comment by usersxm** [comment]
yes, I'm using the last one.. But now I'm really messed up.. I tried with yeomen and cpm restore but now I'm getting this error "System.ComponentModel.Win32Exception: ApplicationName='grunt' ........" 
I think I've broken everything because I can make something work, but then something else stops working.. and so on..

So I what I really want to do is delete every single thing, and start everything again.. How can I do that?

Regards

**Comment by peterblazejewicz** [comment]
@usersxm In case of Atom, you can:
- first remove packages using builtin menus first 'View > Toggle Command Palette > Uninstall Packages'
- from system console/terminal:
```
apm uninstall {package-name}
```
- on Mac/*nix open directory:
```
~/.atom/packages
```
and remove a package

These should clear Atom package installation.

If you by chance tried to develop, contribute to package, unlink it:
```
apm unlink {package-name} --hard
```

**Comment by david-driscoll** [comment]
@usersxm are you still having issues, have you tried the steps @peterblazejewicz has given?

Let us know if you need more help.  Also we've recently pushed several large updates, so please get latest of atom and omnisharp-atom to make sure you're using latest!
