### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by usersxm** [OmniSharp/omnisharp-atom#89]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
StatusBarView.initialize (/Users/opera/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/status-bar-view.coffee:25:9)
```

**Comment by usersxm** [comment]
and I do have some other deprecations (36 to be exact).. I cannot get a simple hello world code to build (I think it's because of this)

**Comment by ctolkien** [comment]
Fixed.
