### ISSUE TITLE
Object.add is deprecated.

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/omnisharp-atom#90]
This was taken  from my Atom `Version 0.189.0 (0.189.0)` instance:
> Are you trying to listen for the 'core:confirm' Atom command with `jQuery::on`?
`jQuery::trigger` can no longer be used to listen for Atom commands. Please
use `atom.commands.add` instead. See the docs at
https://atom.io/docs/api/latest/CommandRegistry

**Comment by ctolkien** [comment]
Fixed!
