### ISSUE TITLE
Find a new keybinding to launch OmniSharp from atom

### ISSUE THREAD

**Issue by AndersNS** [OmniSharp/omnisharp-atom#96]
From the 0.190 release notes: 

> There is now an application:add-project-folder command to add a project folder to the current window. It is bound to Cmd-Shift-O on Mac and Ctrl-Alt-O on Linux and Windows. You can also access it from the File menu 
> [Source](https://github.com/atom/atom/releases/tag/v0.190.0)

It is probably poor form to override the editors own keybindings. After a quick test it seems OmniSharp "wins", so it still starts with Ctrl-Alt-O. Disable the omnisharp-atom plugin and Ctrl-Alt-O starts adding project folders as expected. 

Could also be solved by automatically starting OmniSharp. :wink:

**Comment by willl** [comment]
Here's a screenshot of the keybindings settings page. We'll definitely need to make the change at some stage.

![Keybindings screenshot](https://jabbrlive.blob.core.windows.net/jabbr-uploads/clipboard_7204.png)

If we still want to use O to represent OmniSharp. Perhaps we could change it to ctrl-alt-shift-o? So the change is an additional shift key press.

**Comment by willl** [comment]
Perhaps if #123 gets addressed, we may no longer need to start it manually.

**Comment by david-driscoll** [comment]
We should probably still address this fairly soon.  What combination do we want to use?

**Comment by nosami** [comment]
The keybind `ctrl-alt-o` has no effect at all on linux. I have to use the menu to toggle the server.

**Comment by ctolkien** [comment]
What about just `alt-o`? Or `ctrl-shift-o` ?

:+1: on addressing this soon.

**Comment by sgwill** [comment]
I like `ctrl-shift-o`

**Comment by willl** [comment]
`ctrl-shift-o` opens a folder on Windows/Linux.

https://github.com/atom/atom/blob/master/keymaps/win32.cson#L17

**Comment by nosami** [comment]
We have auto-start enabled in v0.4.5 now. So this is only going to be an issue when auto start is disabled

**Comment by ctolkien** [comment]
Sooo funnily enough, now that we have a dependency on atom-yeoman, it too uses `ctrl-alt-o`, which ironically means it breaks our toggler.

**Comment by nosami** [comment]
@david-driscoll should change the binding on atom-yeoman :tongue:

**Comment by david-driscoll** [comment]
yeah... I should.

**Comment by david-driscoll** [comment]
It should be done now.
